// CC-DESC: Deterministically detects project stacks and current file-rule coverage.

using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace ContextControl.Workbench.Services;

public static partial class ProjectStackScanner
{
    private const int MaxDepth = 20;
    private const int MaxDirectories = 8000;
    private const int MaxFiles = 50000;
    private const long MaxManifestReadBytes = 512 * 1024;
    private const long MaxTextSignalReadBytes = 160 * 1024;
    private const int MaxTextSignalFiles = 3000;

    private static readonly StringComparer NameComparer = StringComparer.OrdinalIgnoreCase;
    private static readonly EnumerationOptions SafeEnumerationOptions = new()
    {
        AttributesToSkip = FileAttributes.Hidden | FileAttributes.System,
        IgnoreInaccessible = true,
        RecurseSubdirectories = false
    };
    private static readonly HashSet<string> AlwaysSkippedDirectories = new(NameComparer)
    {
        ".bundle",
        ".cache",
        ".ccReplace.versions",
        ".ccWorkbench.browser-data",
        ".angular",
        ".bloop",
        ".claude",
        ".conan",
        ".conan2",
        ".codex",
        ".cursor",
        ".dart_tool",
        ".expo",
        ".git",
        ".godot",
        ".gptReplace.versions",
        ".gradle",
        ".idea",
        ".import",
        ".metals",
        ".m2",
        ".mypy_cache",
        ".next",
        ".nox",
        ".opam",
        ".nuxt",
        ".nuget",
        ".parcel-cache",
        ".pnpm-store",
        ".pytest_cache",
        ".ruff_cache",
        ".serverless",
        ".svelte-kit",
        ".terraform",
        ".tmp",
        ".tox",
        ".turbo",
        ".venv",
        ".vs",
        ".vscode",
        ".yarn",
        ".zig-cache",
        "__pycache__",
        "_build",
        "_deps",
        "_opam",
        "bazel-bin",
        "bazel-out",
        "bazel-testlogs",
        "bin",
        "bower_components",
        "build",
        "build-debug",
        "build-release",
        "cmake-build-debug",
        "cmake-build-release",
        "CMakeFiles",
        "coverage",
        "DerivedData",
        "deps",
        "dist",
        "elm-stuff",
        "external",
        "extern",
        "node_modules",
        "obj",
        "out",
        "packages",
        "Pods",
        "target",
        "third_party",
        "thirdparty",
        "vendor",
        "vcpkg_installed",
        "venv",
        "zig-out"
    };
    private static readonly HashSet<string> TopLevelBuildConfigurationDirectories = new(NameComparer)
    {
        "Debug",
        "MinSizeRel",
        "Release",
        "RelWithDebInfo",
        "x64"
    };
    private static readonly string[] AutoSetupIgnoredFileNames =
    [
        ".ccFileRules.json",
        ".ccReplace.settings.auto.json",
        ".ccReplace.settings.json",
        ".ccWorkbench.settings.json",
        ".DS_Store",
        "desktop.ini",
        "Thumbs.db"
    ];
    private static readonly string[] AutoSetupIgnoredExtensions =
    [
        ".a",
        ".bak",
        ".bin",
        ".bmp",
        ".cache",
        ".collision",
        ".db",
        ".dds",
        ".dll",
        ".dylib",
        ".exe",
        ".exp",
        ".fc",
        ".fif",
        ".flac",
        ".gz",
        ".ico",
        ".ilk",
        ".import",
        ".ipch",
        ".jar",
        ".jpeg",
        ".jpg",
        ".lastbuildstate",
        ".lib",
        ".log",
        ".mp3",
        ".o",
        ".obj",
        ".ogg",
        ".opendb",
        ".pdb",
        ".pdf",
        ".png",
        ".pyc",
        ".pyo",
        ".rar",
        ".sdf",
        ".snapshot",
        ".so",
        ".spv",
        ".svo",
        ".tga",
        ".tlog",
        ".tmp",
        ".ttf",
        ".uid",
        ".unsuccessfulbuild",
        ".wasm",
        ".wav",
        ".webp",
        ".zip"
    ];

    private static readonly Dictionary<string, string> LanguageByExtension = new(NameComparer)
    {
        [".asm"] = "Assembly",
        [".astro"] = "Astro",
        [".axaml"] = "Avalonia XAML",
        [".bash"] = "Shell",
        [".bat"] = "Batch",
        [".bzl"] = "Starlark",
        [".c"] = "C",
        [".cc"] = "C++",
        [".cjs"] = "JavaScript",
        [".clj"] = "Clojure",
        [".cljc"] = "Clojure",
        [".cljs"] = "ClojureScript",
        [".coffee"] = "CoffeeScript",
        [".cpp"] = "C++",
        [".cs"] = "C#",
        [".cshtml"] = "Razor",
        [".cts"] = "TypeScript",
        [".cmd"] = "Batch",
        [".css"] = "CSS",
        [".cu"] = "CUDA",
        [".cuh"] = "CUDA",
        [".cxx"] = "C++",
        [".dart"] = "Dart",
        [".elm"] = "Elm",
        [".erl"] = "Erlang",
        [".ex"] = "Elixir",
        [".exs"] = "Elixir",
        [".fs"] = "F#",
        [".fsi"] = "F#",
        [".fsx"] = "F#",
        [".gd"] = "GDScript",
        [".go"] = "Go",
        [".gradle"] = "Gradle",
        [".groovy"] = "Groovy",
        [".h"] = "C/C++ header",
        [".hcl"] = "HCL",
        [".hh"] = "C++ header",
        [".hpp"] = "C++ header",
        [".hs"] = "Haskell",
        [".hrl"] = "Erlang",
        [".html"] = "HTML",
        [".hxx"] = "C++ header",
        [".java"] = "Java",
        [".jl"] = "Julia",
        [".js"] = "JavaScript",
        [".jsx"] = "React JSX",
        [".jsonnet"] = "Jsonnet",
        [".kt"] = "Kotlin",
        [".kts"] = "Kotlin",
        [".lhs"] = "Haskell",
        [".lua"] = "Lua",
        [".m"] = "Objective-C",
        [".mjs"] = "JavaScript",
        [".ml"] = "OCaml",
        [".mli"] = "OCaml",
        [".mm"] = "Objective-C++",
        [".mts"] = "TypeScript",
        [".nasm"] = "Assembly",
        [".nim"] = "Nim",
        [".pas"] = "Pascal",
        [".php"] = "PHP",
        [".pl"] = "Perl",
        [".pm"] = "Perl",
        [".ps1"] = "PowerShell",
        [".psd1"] = "PowerShell",
        [".psm1"] = "PowerShell",
        [".py"] = "Python",
        [".r"] = "R",
        [".raku"] = "Raku",
        [".razor"] = "Razor",
        [".rb"] = "Ruby",
        [".rmd"] = "R Markdown",
        [".rs"] = "Rust",
        [".s"] = "Assembly",
        [".sbt"] = "Scala",
        [".sc"] = "Scala",
        [".scala"] = "Scala",
        [".scss"] = "SCSS",
        [".sh"] = "Shell",
        [".sql"] = "SQL",
        [".svelte"] = "Svelte",
        [".swift"] = "Swift",
        [".tf"] = "Terraform",
        [".tfvars"] = "Terraform",
        [".ts"] = "TypeScript",
        [".tsx"] = "React TSX",
        [".vb"] = "VB.NET",
        [".vue"] = "Vue",
        [".xaml"] = "XAML",
        [".zig"] = "Zig",
        [".zon"] = "Zig",
        [".zsh"] = "Shell"
    };

    private static readonly Dictionary<string, string[]> SuggestedSupportedByStack = new(NameComparer)
    {
        [".NET"] = [".cs", ".csproj", ".fs", ".fsproj", ".props", ".sln", ".targets", ".vb", ".vbproj", ".json", ".xml"],
        [".NET MAUI"] = [".cs", ".csproj", ".json", ".props", ".sln", ".targets", ".xaml", ".xml"],
        ["Angular"] = [".ts", ".html", ".css", ".scss", ".json", ".yaml", ".yml"],
        ["Assembly"] = [".asm", ".s", ".nasm", ".inc"],
        ["ASP.NET Core"] = [".cs", ".cshtml", ".razor", ".csproj", ".json", ".css", ".html", ".js"],
        ["Astro"] = [".astro", ".ts", ".tsx", ".js", ".jsx", ".json", ".css", ".md"],
        ["Avalonia UI"] = [".axaml", ".cs", ".csproj", ".json"],
        ["Batch"] = [".bat", ".cmd"],
        ["Bazel"] = [".bzl"],
        ["C/C++"] = [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".cmake", ".txt"],
        ["Clojure"] = [".clj", ".cljs", ".cljc", ".edn"],
        ["CoffeeScript"] = [".coffee", ".js", ".json"],
        ["CUDA"] = [".cu", ".cuh", ".c", ".cc", ".cpp", ".h", ".hpp", ".cmake"],
        ["Dart"] = [".dart", ".yaml", ".yml"],
        ["Deno"] = [".ts", ".tsx", ".js", ".jsx", ".json", ".jsonc", ".css", ".html", ".md"],
        ["Docker"] = [".dockerignore", ".yaml", ".yml"],
        ["Electron"] = [".ts", ".tsx", ".js", ".jsx", ".json", ".html", ".css"],
        ["Elixir"] = [".ex", ".exs"],
        ["Elm"] = [".elm", ".json"],
        ["Erlang"] = [".erl", ".hrl", ".config", ".lock"],
        ["F#"] = [".fs", ".fsi", ".fsx", ".fsproj", ".sln", ".props", ".targets", ".json"],
        ["Flutter"] = [".dart", ".yaml", ".yml"],
        ["Go"] = [".go", ".mod", ".sum"],
        ["Godot"] = [".gd", ".tscn", ".tres", ".godot", ".cfg"],
        ["Groovy"] = [".groovy", ".gradle", ".json", ".yaml", ".yml"],
        ["Haskell"] = [".hs", ".lhs", ".cabal", ".yaml", ".yml"],
        ["Java"] = [".java", ".gradle", ".kts", ".xml", ".properties"],
        ["JavaScript"] = [".js", ".jsx", ".mjs", ".cjs", ".json", ".css", ".html", ".md", ".yaml", ".yml"],
        ["Julia"] = [".jl", ".toml"],
        ["Kotlin"] = [".kt", ".kts", ".gradle", ".xml", ".properties"],
        ["Lua"] = [".lua", ".rockspec"],
        ["Next.js"] = [".ts", ".tsx", ".js", ".jsx", ".json", ".css", ".scss", ".html", ".md"],
        ["Nim"] = [".nim", ".nimble"],
        ["Node.js"] = [".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".json", ".css", ".html", ".md", ".yaml", ".yml"],
        ["Nuxt"] = [".vue", ".ts", ".js", ".json", ".css", ".scss", ".md"],
        ["Objective-C"] = [".m", ".mm", ".h", ".hpp", ".swift", ".json", ".plist"],
        ["OCaml"] = [".ml", ".mli", ".opam"],
        ["Pascal"] = [".pas"],
        ["Perl"] = [".pl", ".pm"],
        ["PHP"] = [".php", ".json"],
        ["Python"] = [".py", ".toml", ".txt", ".ini", ".cfg", ".yaml", ".yml"],
        ["R"] = [".r", ".rmd", ".rproj", ".lock"],
        ["Raku"] = [".raku"],
        ["React"] = [".tsx", ".ts", ".jsx", ".js", ".json", ".css", ".html", ".md"],
        ["Ruby"] = [".rb", ".gemspec", ".lock", ".yml", ".yaml"],
        ["Rust"] = [".rs", ".toml", ".lock"],
        ["Scala"] = [".scala", ".sc", ".sbt", ".xml", ".properties"],
        ["Shell"] = [".sh", ".bash", ".zsh"],
        ["SQL"] = [".sql"],
        ["Swift"] = [".swift", ".json"],
        ["Terraform"] = [".tf", ".tfvars", ".hcl"],
        ["TypeScript"] = [".ts", ".tsx", ".js", ".jsx", ".json"],
        ["Unity"] = [".cs", ".asmdef", ".shader", ".json"],
        ["Vite"] = [".ts", ".tsx", ".js", ".jsx", ".vue", ".svelte", ".json", ".css", ".html"],
        ["Vue"] = [".vue", ".ts", ".js", ".json", ".css"],
        ["Xamarin"] = [".cs", ".csproj", ".json", ".props", ".sln", ".targets", ".xaml", ".xml"],
        ["Svelte"] = [".svelte", ".ts", ".js", ".json", ".css"],
        ["PowerShell"] = [".ps1", ".psm1", ".psd1"],
        ["Zig"] = [".zig", ".zon"]
    };

    private static readonly Dictionary<string, string[]> SuggestedLocByStack = new(NameComparer)
    {
        [".NET"] = [".cs", ".fs", ".vb"],
        [".NET MAUI"] = [".cs", ".xaml"],
        ["Angular"] = [".ts"],
        ["Assembly"] = [".asm", ".s", ".nasm", ".inc"],
        ["ASP.NET Core"] = [".cs", ".cshtml", ".razor"],
        ["Astro"] = [".astro", ".ts", ".js"],
        ["Avalonia UI"] = [".axaml", ".cs"],
        ["Batch"] = [".bat", ".cmd"],
        ["Bazel"] = [".bzl"],
        ["C/C++"] = [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"],
        ["Clojure"] = [".clj", ".cljs", ".cljc"],
        ["CoffeeScript"] = [".coffee"],
        ["CUDA"] = [".cu", ".cuh"],
        ["Dart"] = [".dart"],
        ["Deno"] = [".ts", ".tsx", ".js", ".jsx"],
        ["Electron"] = [".ts", ".tsx", ".js", ".jsx"],
        ["Elixir"] = [".ex", ".exs"],
        ["Elm"] = [".elm"],
        ["Erlang"] = [".erl", ".hrl"],
        ["F#"] = [".fs", ".fsi", ".fsx"],
        ["Flutter"] = [".dart"],
        ["Go"] = [".go"],
        ["Godot"] = [".gd"],
        ["Groovy"] = [".groovy", ".gradle"],
        ["Haskell"] = [".hs", ".lhs"],
        ["Java"] = [".java"],
        ["JavaScript"] = [".js", ".jsx", ".mjs", ".cjs"],
        ["Julia"] = [".jl"],
        ["Kotlin"] = [".kt", ".kts"],
        ["Lua"] = [".lua"],
        ["Next.js"] = [".ts", ".tsx", ".js", ".jsx"],
        ["Nim"] = [".nim"],
        ["Node.js"] = [".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"],
        ["Nuxt"] = [".vue", ".ts", ".js"],
        ["Objective-C"] = [".m", ".mm", ".h"],
        ["OCaml"] = [".ml", ".mli"],
        ["Pascal"] = [".pas"],
        ["Perl"] = [".pl", ".pm"],
        ["PHP"] = [".php"],
        ["Python"] = [".py"],
        ["R"] = [".r", ".rmd"],
        ["Raku"] = [".raku"],
        ["React"] = [".tsx", ".ts", ".jsx", ".js"],
        ["Ruby"] = [".rb"],
        ["Rust"] = [".rs"],
        ["Scala"] = [".scala", ".sc", ".sbt"],
        ["Shell"] = [".sh", ".bash", ".zsh"],
        ["SQL"] = [".sql"],
        ["Swift"] = [".swift"],
        ["Svelte"] = [".svelte", ".ts", ".js"],
        ["Terraform"] = [".tf", ".tfvars", ".hcl"],
        ["TypeScript"] = [".ts", ".tsx"],
        ["Unity"] = [".cs"],
        ["Vite"] = [".ts", ".tsx", ".js", ".jsx", ".vue", ".svelte"],
        ["Vue"] = [".vue", ".ts", ".js"],
        ["Xamarin"] = [".cs", ".xaml"],
        ["PowerShell"] = [".ps1", ".psm1", ".psd1"],
        ["Zig"] = [".zig"]
    };

    private static readonly Dictionary<string, string[]> SuggestedSkippedDirectoriesByStack = new(NameComparer)
    {
        [".NET"] = ["bin", "obj", ".vs", "TestResults"],
        [".NET MAUI"] = ["bin", "obj", ".vs", "TestResults"],
        ["Angular"] = ["node_modules", "dist", "build", "coverage", ".angular"],
        ["ASP.NET Core"] = ["bin", "obj", ".vs", "TestResults", "wwwroot/lib"],
        ["Astro"] = ["node_modules", "dist", "build", ".astro"],
        ["Bazel"] = ["bazel-bin", "bazel-out", "bazel-testlogs"],
        ["C/C++"] = ["build", "cmake-build-debug", "cmake-build-release", "CMakeFiles"],
        ["Clojure"] = ["target", ".cpcache"],
        ["CUDA"] = ["build", "cmake-build-debug", "cmake-build-release", "CMakeFiles"],
        ["Dart"] = [".dart_tool", "build"],
        ["Deno"] = [".deno", "dist", "coverage"],
        ["Docker"] = [],
        ["Electron"] = ["node_modules", "dist", "build", "out"],
        ["Elixir"] = ["_build", "deps"],
        ["Elm"] = ["elm-stuff"],
        ["Erlang"] = ["_build", "deps"],
        ["Flutter"] = [".dart_tool", "build"],
        ["Go"] = ["vendor"],
        ["Godot"] = [".godot", ".import"],
        ["Haskell"] = [".stack-work", "dist", "dist-newstyle"],
        ["Java"] = [".gradle", "build", "target", "out"],
        ["JavaScript"] = ["node_modules", "dist", "build", "coverage"],
        ["Julia"] = [".julia"],
        ["Kotlin"] = [".gradle", "build", "target", "out"],
        ["Next.js"] = ["node_modules", ".next", "out", "dist", "build", "coverage"],
        ["Nim"] = ["nimcache"],
        ["Node.js"] = ["node_modules", "dist", "build", "coverage", ".next", ".nuxt", ".svelte-kit", ".turbo"],
        ["Nuxt"] = ["node_modules", ".nuxt", "dist", "build", "coverage"],
        ["OCaml"] = ["_build", "_opam"],
        ["PHP"] = ["vendor"],
        ["Python"] = [".venv", "venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"],
        ["R"] = ["renv/library", "packrat/lib"],
        ["React"] = ["node_modules", "dist", "build", "coverage"],
        ["Ruby"] = [".bundle", "vendor/bundle", "tmp"],
        ["Rust"] = ["target"],
        ["Scala"] = ["target", ".bloop", ".metals"],
        ["Swift"] = [".build", "DerivedData", "Pods"],
        ["Terraform"] = [".terraform"],
        ["Vite"] = ["node_modules", "dist", "build", "coverage"],
        ["Xamarin"] = ["bin", "obj", ".vs", "TestResults"],
        ["Zig"] = [".zig-cache", "zig-out"],
        ["Unity"] = ["Library", "Temp", "Obj", "Build", "Builds", "Logs"]
    };

    private static readonly HashSet<string> SourceOrConfigSuggestionExtensions = BuildSourceOrConfigSuggestionExtensions();
    private static readonly HashSet<string> TextSignalExtensions = new(NameComparer)
    {
        ".c",
        ".cc",
        ".cmake",
        ".cpp",
        ".cs",
        ".cxx",
        ".dart",
        ".bzl",
        ".ex",
        ".exs",
        ".fs",
        ".fsi",
        ".fsx",
        ".go",
        ".gradle",
        ".groovy",
        ".h",
        ".hh",
        ".hpp",
        ".hs",
        ".hxx",
        ".java",
        ".jl",
        ".js",
        ".jsx",
        ".kt",
        ".kts",
        ".lua",
        ".m",
        ".mjs",
        ".ml",
        ".mli",
        ".mm",
        ".mts",
        ".nim",
        ".php",
        ".pl",
        ".pm",
        ".ps1",
        ".py",
        ".r",
        ".rb",
        ".rs",
        ".scala",
        ".sh",
        ".toml",
        ".ts",
        ".tsx",
        ".tf",
        ".tfvars",
        ".vb",
        ".vue",
        ".zig",
        ".yaml",
        ".yml"
    };
    private static readonly TechnologyPattern[] TextUsePatterns =
    [
        new("Vulkan", ["<vulkan/vulkan.h>", "Vulkan::Vulkan", "VK_", "VkInstance", "VkDevice", "VkCommandBuffer"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".m", ".mm"]),
        new("GLFW", ["<GLFW/glfw3.h>", "GLFWwindow", "glfwInit"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("GLM", ["<glm/", "glm::"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("Dear ImGui", ["<imgui.h>", "ImGui::", "imgui_impl", "imgui_impl_vulkan"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("Jolt Physics", ["<Jolt/", "JPH::"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("EnTT", ["<entt/", "entt::"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("STB", ["stb_image", "stb_image.h", "stb_truetype"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("spdlog", ["<spdlog/", "spdlog::"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("fmt", ["<fmt/", "fmt::"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("OpenGL", ["<GL/gl", "<glad/", "gladLoadGL", "glewInit"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("SDL", ["<SDL.h>", "<SDL2/", "SDL_Init", "SDL_Window"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("Direct3D 12", ["d3d12.h", "ID3D12"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("Direct3D 11", ["d3d11.h", "ID3D11"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]),
        new("Metal", ["<Metal/Metal.h>", "MTLDevice", "CAMetalLayer"], [".m", ".mm", ".h", ".hpp"]),
        new("CUDA", ["cuda_runtime.h", "__global__", "cudaMalloc"], [".cu", ".cuh", ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"]),
        new("OpenCV", ["<opencv2/", "cv::Mat", "import cv2"], [".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".py"]),
        new("PyTorch", ["import torch", "from torch", "torch::"], [".py", ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"]),
        new("TensorFlow", ["import tensorflow", "from tensorflow", "tensorflow/core"], [".py", ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"]),
        new("React", ["from 'react'", "from \"react\"", "ReactDOM"], [".js", ".jsx", ".ts", ".tsx"]),
        new("Vue", ["from 'vue'", "from \"vue\"", "createApp("], [".js", ".jsx", ".ts", ".tsx", ".vue"]),
        new("Svelte", ["from 'svelte", "@sveltejs/"], [".js", ".jsx", ".ts", ".tsx", ".svelte"])
    ];
}
