// CC-DESC: Cloud/frontier and Mistral-family catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CloudAndFrontierCatalog { get; } =
    [
        CatalogModel(
            "rnj-1:8b-cloud",
            "RNJ-1 8B Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Open-weight",
            "Ollama account/cloud access; no local VRAM",
            "32K",
            "8K-16K practical via cloud",
            EightKSourceBudget,
            "Cloud code/STEM tool model",
            "Cloud RNJ route for coding agents and STEM tasks without a local install.",
            0,
            0,
            true),
        CatalogModel(
            "kimi-k2.6:cloud",
            "Kimi K2.6 Cloud",
            "Apr 2026",
            "",
            "Ollama Cloud",
            "Moonshot AI License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud multimodal agentic model",
            "Long-horizon coding, UI generation from visual input, and large agent orchestration.",
            0,
            0,
            true),
        CatalogModel(
            "kimi-k2-thinking:cloud",
            "Kimi K2 Thinking Cloud",
            "Nov 2025",
            "",
            "Ollama Cloud",
            "Moonshot AI License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud thinking agent model",
            "Deep reasoning, browsing/search-style agents, coding, and multi-step tool workflows.",
            0,
            0,
            true),
        CatalogModel(
            "kimi-k2.5:cloud",
            "Kimi K2.5 Cloud",
            "Sep 2025",
            "",
            "Ollama Cloud",
            "Moonshot AI License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud multimodal Kimi model",
            "Previous Kimi multimodal agent route for image/text workflows, coding, and long context.",
            0,
            0,
            true),
        CatalogModel(
            "kimi-k2:1t-cloud",
            "Kimi K2 1T Cloud",
            "Sep 2025",
            "",
            "Ollama Cloud",
            "Moonshot AI License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud Kimi MoE coding model",
            "Kimi K2 Instruct route for real-world coding agents and long-context assistant work.",
            0,
            0,
            true),
        CatalogModel(
            "minimax-m2.7:cloud",
            "MiniMax M2.7 Cloud",
            "Mar 2026",
            "",
            "Ollama Cloud",
            "MiniMax License",
            "Ollama account/cloud access; no local VRAM",
            "200K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud coding and productivity agent",
            "Professional coding, document work, troubleshooting, and long-horizon agent workflows.",
            0,
            0,
            true),
        CatalogModel(
            "minimax-m2.5:cloud",
            "MiniMax M2.5 Cloud",
            "Feb 2026",
            "",
            "Ollama Cloud",
            "MiniMax License",
            "Ollama account/cloud access; no local VRAM",
            "198K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud coding/productivity agent",
            "MiniMax M2.5 route for coding, office/productivity tasks, and long-horizon agent workflows.",
            0,
            0,
            true),
        CatalogModel(
            "minimax-m2.1:cloud",
            "MiniMax M2.1 Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "MiniMax License",
            "Ollama account/cloud access; no local VRAM",
            "200K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud multilingual coding agent",
            "Earlier MiniMax M2 route for cross-language software engineering and agent tasks.",
            0,
            0,
            true),
        CatalogModel(
            "mistral-medium-3.5:128b-q4_K_M",
            "Mistral Medium 3.5 128B Q4",
            "May 2026",
            "",
            "~80 GB Q4",
            "Modified MIT",
            "128 GB+ RAM; multi-GPU/server preferred",
            "256K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Flagship Mistral unified model",
            "Instruction following, reasoning, coding, vision, and agentic work in one large open-weight model.",
            80,
            96,
            false),
        CatalogModel(
            "mistral-large-3:675b-cloud",
            "Mistral Large 3 Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Mistral AI License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud production multimodal MoE",
            "Enterprise-grade multilingual chat, vision, function calling, JSON, and agentic tasks.",
            0,
            0,
            true),
        CatalogModel(
            "devstral-small-2:24b",
            "Devstral Small 2 24B",
            "Dec 2025",
            "",
            "~15 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "384K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Updated coding-agent model",
            "Newer Devstral route for codebase exploration, multi-file edits, and vision-aware software tasks.",
            20,
            24,
            false),
        CatalogModel(
            "devstral-small-2:24b-cloud",
            "Devstral Small 2 24B Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud coding-agent model",
            "Run updated Devstral agentic coding workflows without local 24B memory pressure.",
            0,
            0,
            true),
        CatalogModel(
            "devstral-2:123b",
            "Devstral 2 123B",
            "Feb 2026",
            "",
            "~75 GB Q4",
            "Apache 2.0",
            "128 GB+ RAM; multi-GPU/server preferred",
            "256K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large coding-agent model",
            "Server-class Devstral for software engineering agents, repo exploration, and multi-file editing.",
            72,
            96,
            false),
        CatalogModel(
            "devstral-2:123b-cloud",
            "Devstral 2 123B Cloud",
            "Feb 2026",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud large coding-agent model",
            "High-capability Devstral route for repo-scale work through Ollama Cloud.",
            0,
            0,
            true),
        CatalogModel(
            "ministral-3:8b",
            "Ministral 3 8B",
            "Dec 2025",
            "",
            "~6.0 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "256K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Balanced edge vision/tool model",
            "Mistral edge chat, image notes, tool calls, and local assistant workflows.",
            6.5,
            8,
            false),
        CatalogModel(
            "ministral-3:14b",
            "Ministral 3 14B",
            "Dec 2025",
            "",
            "~9.1 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "256K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Larger edge vision/tool model",
            "Stronger multimodal Mistral route for local assistant, image, and tool workflows.",
            10,
            12,
            false),
        CatalogModel(
            "ministral-3:3b-cloud",
            "Ministral 3 3B Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "8K-16K practical via cloud",
            EightKSourceBudget,
            "Cloud small Mistral edge model",
            "Low-usage cloud route for small multimodal tool tasks.",
            0,
            0,
            true),
        CatalogModel(
            "ministral-3:8b-cloud",
            "Ministral 3 8B Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "8K-16K practical via cloud",
            EightKSourceBudget,
            "Cloud balanced Mistral edge model",
            "Cloud route for Ministral 8B multimodal chat and tool workflows.",
            0,
            0,
            true),
        CatalogModel(
            "ministral-3:14b-cloud",
            "Ministral 3 14B Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "8K-16K practical via cloud",
            EightKSourceBudget,
            "Cloud larger Mistral edge model",
            "Cloud route for stronger Ministral multimodal chat, screenshots, and tool use.",
            0,
            0,
            true),
        CatalogModel(
            "mixtral:8x7b",
            "Mixtral 8x7B",
            "Dec 2023",
            "",
            "~26 GB Q4",
            "Apache 2.0",
            "64 GB RAM; 32 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Classic Mistral MoE",
            "Important open MoE baseline for multilingual chat, coding, and instruction following.",
            24,
            32,
            false),
        CatalogModel(
            "mixtral:8x22b",
            "Mixtral 8x22B",
            "Apr 2024",
            "",
            "~80 GB Q4",
            "Apache 2.0",
            "128 GB+ RAM; multi-GPU/server preferred",
            "64K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large classic Mistral MoE",
            "Server-class Mixtral baseline for multilingual chat, coding, and long-form analysis.",
            64,
            80,
            false),
    ];
}
