// CC-DESC: Qwen Ollama catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> QwenOllamaCatalog { get; } =
    [
        CatalogModel(
            "qwen2.5-coder:0.5b",
            "Qwen2.5 Coder 0.5B",
            "Nov 12, 2024",
            QwenIconSource,
            "~398 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Very fast on CPU or small GPUs",
            "Tiny file classification, rough summaries, and routing hints.",
            0,
            1,
            true),
        CatalogModel(
            "qwen2.5-coder:1.5b",
            "Qwen2.5 Coder 1.5B",
            "Nov 12, 2024",
            QwenIconSource,
            "~986 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works; 2 GB+ VRAM is comfortable",
            "32K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Fast on 4 GB VRAM; good CPU fallback",
            "Fast classifier, file summary, folder responsibility detection, tiny edits.",
            0,
            2,
            true),
        CatalogModel(
            "qwen2.5-coder:3b",
            "Qwen2.5 Coder 3B",
            "Nov 12, 2024",
            QwenIconSource,
            "~1.9 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "Best local CC fit for style detection, small patches, and patch review.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen2.5-coder:7b",
            "Qwen2.5 Coder 7B",
            "Nov 12, 2024",
            QwenIconSource,
            "~4.7 GB Q4",
            "Apache 2.0",
            "12 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+; avoid on 4 GB",
            EightKSourceBudget,
            "Slow/offloaded on 4 GB; good on 8 GB+",
            "Stronger coding model for 8 GB+ GPUs, not a good fit for fast 4 GB use.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen2.5-coder:14b",
            "Qwen2.5 Coder 14B",
            "Nov 12, 2024",
            QwenIconSource,
            "~9.0 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Larger refactors and reviews when 8 GB class models are too shallow.",
            12,
            16,
            false),
        CatalogModel(
            "qwen2.5-coder:32b",
            "Qwen2.5 Coder 32B",
            "Nov 12, 2024",
            QwenIconSource,
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class local model",
            "Deep coding review and multi-file reasoning on high-memory machines.",
            20,
            24,
            false),

        CatalogModel(
            "qwen3:0.6b",
            "Qwen3 0.6B",
            "Apr 29, 2025",
            QwenIconSource,
            "~523 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "40K",
            "4K safe",
            FourKSourceBudget,
            "Very fast",
            "Tiny general chat, intent classification, and cheap project notes.",
            0,
            1,
            true),
        CatalogModel(
            "qwen3:1.7b",
            "Qwen3 1.7B",
            "Apr 29, 2025",
            QwenIconSource,
            "~1.4 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "40K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast on CPU or small GPUs",
            "General explanations and short chat turns with low local cost.",
            0,
            2,
            true),
        CatalogModel(
            "qwen3:4b",
            "Qwen3 4B",
            "Apr 29, 2025",
            QwenIconSource,
            "~2.5 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "General reasoning, review notes, and chat when code-specialization is less important.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen3:8b",
            "Qwen3 8B",
            "Apr 29, 2025",
            QwenIconSource,
            "~5.2 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "40K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Balanced local chat and reasoning with better depth than 4B models.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen3:14b",
            "Qwen3 14B",
            "Apr 29, 2025",
            QwenIconSource,
            "~9.3 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "40K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Richer general reasoning and longer architecture discussions.",
            12,
            16,
            false),
        CatalogModel(
            "qwen3:30b",
            "Qwen3 30B-A3B",
            "Apr 29, 2025",
            QwenIconSource,
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Mixture-of-experts; large local footprint",
            "High-depth reasoning when you can afford the load and memory.",
            20,
            24,
            false),
        CatalogModel(
            "qwen3:32b",
            "Qwen3 32B",
            "Apr 29, 2025",
            QwenIconSource,
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "40K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class local model",
            "General reasoning and broad review passes on high-memory machines.",
            20,
            24,
            false),
        CatalogModel(
            "qwen3:235b",
            "Qwen3 235B-A22B",
            "Apr 29, 2025",
            QwenIconSource,
            "~142 GB Q4",
            "Apache 2.0",
            "256 GB RAM; multi-GPU recommended",
            "256K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class local model",
            "Experimental top-end local reasoning for very large systems.",
            160,
            200,
            false),
        CatalogModel(
            "qwen3-coder:30b",
            "Qwen3 Coder 30B-A3B",
            "Jul 22, 2025",
            QwenIconSource,
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large but efficient MoE coder",
            "Agentic coding, refactors, and careful patch review on large local setups.",
            20,
            24,
            false),
        CatalogModel(
            "qwen3-coder:480b",
            "Qwen3 Coder 480B-A35B",
            "Jul 22, 2025",
            QwenIconSource,
            "~290 GB Q4",
            "Apache 2.0",
            "384 GB RAM; multi-GPU/server recommended",
            "256K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class coder",
            "Extreme local agentic coding experiments on specialized hardware.",
            320,
            360,
            false),
        CatalogModel(
            "qwen3-next:80b",
            "Qwen3 Next 80B-A3B",
            "Dec 2025",
            QwenIconSource,
            "~50 GB Q4",
            "Apache 2.0",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large MoE general model",
            "Efficient high-depth reasoning and long-context review on large local setups.",
            48,
            64,
            false),
        CatalogModel(
            "qwen3-coder-next",
            "Qwen3 Coder Next 80B-A3B",
            "Feb 2026",
            QwenIconSource,
            "~52 GB Q4",
            "Apache 2.0",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large MoE coder",
            "Newer agentic coding model for repository-scale work on high-memory machines.",
            48,
            64,
            false),
        CatalogModel(
            "qwen3-vl:2b",
            "Qwen3 VL 2B",
            "Nov 2025",
            QwenIconSource,
            "~1.9 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast vision-language model",
            "Small multimodal chat and image-grounded code/design review.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen3-vl:4b",
            "Qwen3 VL 4B",
            "Nov 2025",
            QwenIconSource,
            "~3.3 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "Compact multimodal reasoning and UI screenshot explanation.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen3-vl:8b",
            "Qwen3 VL 8B",
            "Nov 2025",
            QwenIconSource,
            "~6.1 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "256K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Balanced multimodal chat, OCR, screenshots, and code-from-image workflows.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen3-vl:30b",
            "Qwen3 VL 30B-A3B",
            "Nov 2025",
            QwenIconSource,
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large multimodal MoE",
            "Stronger visual coding and document/UI reasoning on high-memory machines.",
            20,
            24,
            false),
        CatalogModel(
            "qwen3-vl:32b",
            "Qwen3 VL 32B",
            "Nov 2025",
            QwenIconSource,
            "~21 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large multimodal dense model",
            "Deep visual reasoning, screenshot interpretation, and architecture review.",
            20,
            24,
            false),
        CatalogModel(
            "qwen3-vl:235b",
            "Qwen3 VL 235B-A22B",
            "Nov 2025",
            QwenIconSource,
            "~143 GB Q4",
            "Apache 2.0",
            "256 GB RAM; multi-GPU recommended",
            "256K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class multimodal model",
            "Top-end open multimodal reasoning on specialized local hardware.",
            160,
            200,
            false),

    ];
}
