// CC-DESC: Research, multilingual, and enterprise catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> ResearchAndMultilingualCatalog { get; } =
    [
        CatalogModel(
            "nemotron-3-super:120b-a12b-q4_K_M",
            "Nemotron 3 Super 120B-A12B Q4",
            "Mar 2026",
            "",
            "~87 GB Q4",
            "NVIDIA Open Model License",
            "128 GB+ RAM; multi-GPU/server preferred",
            "256K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large open MoE agent model",
            "NVIDIA reasoning/agent model for complex multi-agent applications and enterprise workflows.",
            80,
            96,
            false),
        CatalogModel(
            "nemotron-3-super:cloud",
            "Nemotron 3 Super Cloud",
            "Mar 2026",
            "",
            "Ollama Cloud",
            "NVIDIA Open Model License",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud Nemotron agent model",
            "Use Nemotron 3 Super without local server hardware for agentic and enterprise-style tasks.",
            0,
            0,
            true),
        CatalogModel(
            "gemma4:e2b",
            "Gemma 4 E2B",
            "Apr 2026",
            "",
            "~7.2 GB Q4",
            "Gemma Terms of Use",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+; avoid on 4 GB VRAM",
            EightKSourceBudget,
            "On-device multimodal reasoner",
            "Small Gemma 4 route for image-aware chat, reasoning, function calling, and local assistant work.",
            7,
            8,
            false),
        CatalogModel(
            "gemma4:e4b",
            "Gemma 4 E4B",
            "Apr 2026",
            "",
            "~9.6 GB Q4",
            "Gemma Terms of Use",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Stronger on-device Gemma 4",
            "Local multimodal reasoning, coding, tool use, and longer chat when memory allows.",
            10,
            12,
            false),
        CatalogModel(
            "gemma4:26b",
            "Gemma 4 26B",
            "Apr 2026",
            "",
            "~18 GB Q4",
            "Gemma Terms of Use",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Medium Gemma 4 multimodal model",
            "Larger Gemma reasoning, visual understanding, coding, and agent tasks.",
            18,
            24,
            false),
        CatalogModel(
            "gemma4:31b",
            "Gemma 4 31B",
            "Apr 2026",
            "",
            "~20 GB Q4",
            "Gemma Terms of Use",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Largest local Gemma 4 option",
            "High-memory Gemma route for multimodal reasoning, coding, and autonomous assistant work.",
            20,
            24,
            false),
        CatalogModel(
            "gemma4:31b-cloud",
            "Gemma 4 31B Cloud",
            "Apr 2026",
            "",
            "Ollama Cloud",
            "Gemma Terms of Use",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud Gemma 4 route",
            "Run the strongest Gemma 4 chat, vision, coding, and reasoning workflow without local 24 GB VRAM.",
            0,
            0,
            true),
        CatalogModel(
            "translategemma:4b",
            "TranslateGemma 4B",
            "Jan 2026",
            "",
            "~3.3 GB Q4",
            "Gemma Terms of Use",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe; 8K if memory leaves room",
            FourKSourceBudget,
            "Open translation model",
            "Translation-focused Gemma model for English and broad multilingual localization workflows.",
            3.5,
            4,
            true),
        CatalogModel(
            "translategemma:12b",
            "TranslateGemma 12B",
            "Jan 2026",
            "",
            "~8.1 GB Q4",
            "Gemma Terms of Use",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Mid-size open translation model",
            "Higher-quality translation/localization and multilingual assistant work with English support.",
            10,
            12,
            false),
        CatalogModel(
            "translategemma:27b",
            "TranslateGemma 27B",
            "Jan 2026",
            "",
            "~17 GB Q4",
            "Gemma Terms of Use",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large open translation model",
            "High-memory translation, multilingual review, and localization workflows.",
            18,
            24,
            false),
        CatalogModel(
            "functiongemma:270m",
            "FunctionGemma 270M",
            "May 2026",
            "",
            "~301 MB Q8",
            "Gemma Terms of Use",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny function-calling specialist",
            "Very small tool-call and routing experiments where general chat quality is secondary.",
            0,
            1,
            true),
        CatalogModel(
            "exaone-deep:7.8b",
            "EXAONE Deep 7.8B",
            "Mar 2025",
            "",
            "~4.8 GB Q4",
            "EXAONE License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Korean/English reasoning model",
            "LG reasoning route for math, coding, English/Korean chat, and compact critique tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "exaone-deep:32b",
            "EXAONE Deep 32B",
            "Mar 2025",
            "",
            "~19 GB Q4",
            "EXAONE License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Korean/English reasoning model",
            "High-memory EXAONE route for reasoning, math, coding, and bilingual assistant work.",
            18,
            24,
            false),
        CatalogModel(
            "hf.co/LGAI-EXAONE/EXAONE-4.0-32B-GGUF:Q4_K_M",
            "EXAONE 4.0 32B Q4",
            "Jul 2025",
            "",
            "~17.4 GB Q4",
            "EXAONE License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Unified Korean/English reasoning model",
            "EXAONE 4 route for non-reasoning and reasoning chat, tool use, coding, English, Korean, and Spanish.",
            18,
            24,
            false),
        CatalogModel(
            "granite4.1:3b",
            "Granite 4.1 3B",
            "Apr 2026",
            GraniteIconSource,
            "~2.1 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Enterprise-friendly 3B instruct model",
            "Fresh Granite option for RAG, JSON, tool use, summaries, and compact CC patches.",
            3,
            4,
            true),
        CatalogModel(
            "granite4.1:8b",
            "Granite 4.1 8B",
            "Apr 2026",
            GraniteIconSource,
            "~5.3 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Balanced Granite instruct model",
            "Better enterprise-style coding, RAG, tool calls, and structured output than the micro Granite models.",
            6.5,
            8,
            false),
        CatalogModel(
            "granite4.1:30b",
            "Granite 4.1 30B",
            "Apr 2026",
            GraniteIconSource,
            "~17 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Granite enterprise model",
            "High-memory Granite route for multilingual coding, RAG, JSON, tool use, and long analysis.",
            18,
            24,
            false),
        CatalogModel(
            "laguna-xs.2:q4_K_M",
            "Laguna XS.2 33B-A3B Q4",
            "May 2026",
            "",
            "~23 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Local agentic coding MoE",
            "Long-horizon local coding, tool-thinking, and repo work with low active-parameter compute.",
            22,
            24,
            false),
        CatalogModel(
            "olmo-3.1:32b-instruct",
            "OLMo 3.1 32B Instruct",
            "Dec 2025",
            "",
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "64K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Open science instruct model",
            "Transparent open model for coding, chat, and evaluation-friendly local/server work.",
            18,
            24,
            false),
        CatalogModel(
            "olmo-3.1:32b-think",
            "OLMo 3.1 32B Think",
            "Dec 2025",
            "",
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "64K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Open science thinking model",
            "Reasoning-heavy OLMo route for math, coding critique, and careful patch review.",
            18,
            24,
            false),
        CatalogModel(
            "olmo-3:7b-instruct",
            "OLMo 3 7B Instruct",
            "May 2026",
            "",
            "~4.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "64K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Fully open instruct model",
            "Fresh AI2 7B route with open data/code/weights for chat, coding, and transparent evaluation.",
            6.5,
            8,
            false),
        CatalogModel(
            "olmo-3:7b-think",
            "OLMo 3 7B Think",
            "May 2026",
            "",
            "~4.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "64K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Small fully open thinking model",
            "Transparent reasoning route for math, code critique, and careful small-model evaluations.",
            6.5,
            8,
            false),
        CatalogModel(
            "olmo-3:32b-think",
            "OLMo 3 32B Think",
            "May 2026",
            "",
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "64K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large fully open thinking model",
            "AI2 reasoning model for math, coding, transparent research, and higher-memory local evaluation.",
            18,
            24,
            false),
        CatalogModel(
            "tulu3:8b",
            "Tulu 3 8B",
            "Nov 2024",
            "",
            "~4.9 GB Q4",
            "Llama 3.1 Community License; open training recipe",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Open post-training recipe model",
            "AI2 instruction-following model for chat, math, coding, and reproducible post-training comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "tulu3:70b",
            "Tulu 3 70B",
            "Nov 2024",
            "",
            "~43 GB Q4",
            "Llama 3.1 Community License; open training recipe",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Large open post-training recipe model",
            "Large Tulu route for instruction-following, reasoning, and transparent evaluation on big hardware.",
            48,
            64,
            false),

        CatalogModel(
            "hf.co/internlm/internlm3-8b-instruct-gguf:Q4_K_M",
            "InternLM3 8B Instruct Q4",
            "Jan 2025",
            "",
            "~4.9 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Chinese/English instruct model",
            "Asia coverage for bilingual chat, summaries, coding, and general assistant workflows.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/second-state/Yi-1.5-9B-Chat-GGUF:Q4_K_M",
            "Yi 1.5 9B Chat Q4",
            "May 2024",
            "",
            "~5.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Bilingual China chat model",
            "Useful English/Chinese assistant baseline for chat, summaries, and light code.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/ggml-org/Qwen2.5-Omni-7B-GGUF:Q4_K_M",
            "Qwen2.5 Omni 7B Q4",
            "Mar 2025",
            QwenIconSource,
            "~5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Qwen multimodal omni model",
            "Speech/image/text-aware Qwen option for notes, multimodal chat, and local assistant experiments.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/unsloth/Hunyuan-A13B-Instruct-GGUF:Q4_K_M",
            "Hunyuan A13B Instruct Q4",
            "Jun 2025",
            "",
            "~7.8 GB Q4",
            "Tencent Hunyuan License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "32K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Tencent MoE instruct model",
            "China coverage for strong English/Chinese chat, coding, and reasoning on workstation hardware.",
            10,
            12,
            false),
        CatalogModel(
            "hf.co/AyyYOO/MiniCPM4-8B-Q4_K_M-GGUF",
            "MiniCPM4 8B Q4",
            "Jun 2025",
            "",
            "~4.8 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "OpenBMB compact chat model",
            "Small China/Asia model for English-capable chat, summaries, extraction, and local assistant tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/openbmb/MiniCPM5-1B-GGUF:Q4_K_M",
            "MiniCPM5 1B Q4",
            "May 19, 2026",
            "",
            "~688 MB Q4",
            "Apache 2.0",
            "Transformers/llama.cpp manual; Ollama completion-only in current GGUF",
            "128K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Ollama chat blocked until a chat-ready package/template is available",
            "Newest OpenBMB local assistant for coding agents, tool use, and routing; not CC chat-ready through Ollama yet.",
            0,
            2,
            true),
        CatalogModel(
            "hf.co/bartowski/baidu_ERNIE-4.5-21B-A3B-Thinking-GGUF:Q4_K_M",
            "ERNIE 4.5 21B-A3B Thinking Q4",
            "Jun 2025",
            "",
            "~12 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "128K",
            "8K on 16 GB+",
            EightKSourceBudget,
            "Baidu thinking MoE model",
            "China coverage for thinking-mode chat, reasoning, summaries, and multilingual assistant work.",
            12,
            16,
            false),
    ];
}
