// CC-DESC: research, small, and coding local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaResearchSmallCodingCatalog { get; } =
    [
        CatalogModel(
            "glm4:9b",
            "GLM-4 9B",
            "Jun 2024",
            "",
            "~5.5 GB Q4",
            "GLM-4 License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Multilingual general model",
            "Chinese/English multilingual chat, reasoning, and code explanation.",
            6.5,
            8,
            false),
        CatalogModel(
            "nemotron-mini:4b",
            "Nemotron Mini 4B",
            "Sep 2024",
            "",
            "~2.7 GB Q4",
            "NVIDIA Open Model Agreement",
            "8 GB RAM; 4 GB VRAM recommended",
            "4K",
            "4K safe",
            "4K: 150-300 LOC / 8k-12k chars.",
            "Fast small model",
            "RAG QA, roleplay, function-calling experiments, and lightweight chat.",
            3.5,
            4,
            true),
        CatalogModel(
            "nemotron:70b",
            "Llama Nemotron 70B",
            "Oct 2024",
            "",
            "~43 GB Q4",
            "NVIDIA Open Model Agreement; base Llama terms apply",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class helper model",
            "Large-model instruction following and helpfulness-optimized review.",
            48,
            64,
            false),
        CatalogModel(
            "nemotron3:33b",
            "Nemotron 3 Nano Omni 33B",
            "Apr 2026",
            "",
            "~28 GB Q4",
            "NVIDIA Open Model Agreement",
            "64 GB RAM; 48 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "New multimodal enterprise model",
            "Document intelligence, OCR, GUI understanding, and multimodal Q&A.",
            32,
            48,
            false),

        CatalogModel(
            "olmo2:7b",
            "OLMo 2 7B",
            "Nov 2024",
            "",
            "~4.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "4K",
            "4K safe",
            "4K: 150-300 LOC / 8k-12k chars.",
            "Fully-open baseline",
            "Transparent fully-open model for reproducible experiments.",
            6.5,
            8,
            false),
        CatalogModel(
            "olmo2:13b",
            "OLMo 2 13B",
            "Nov 2024",
            "",
            "~8.4 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "4K",
            "4K safe",
            "4K: 150-300 LOC / 8k-12k chars.",
            "Larger fully-open baseline",
            "Transparent fully-open review and general assistant experiments.",
            12,
            16,
            false),
        CatalogModel(
            "falcon3:1b",
            "Falcon 3 1B",
            "Dec 2024",
            "",
            "~1.8 GB Q4",
            "TII Falcon License",
            "4 GB RAM; CPU works",
            "8K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Tiny math/code/science-oriented local assistant.",
            0,
            2,
            true),
        CatalogModel(
            "falcon3:3b",
            "Falcon 3 3B",
            "Dec 2024",
            "",
            "~2.0 GB Q4",
            "TII Falcon License",
            "8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "Small science/math/code-oriented chat and review.",
            3.5,
            4,
            true),
        CatalogModel(
            "falcon3:7b",
            "Falcon 3 7B",
            "Dec 2024",
            "",
            "~4.6 GB Q4",
            "TII Falcon License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Efficient science/math/code-oriented local review.",
            6.5,
            8,
            false),
        CatalogModel(
            "falcon3:10b",
            "Falcon 3 10B",
            "Dec 2024",
            "",
            "~6.3 GB Q4",
            "TII Falcon License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "32K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Good on 12 GB+ GPUs",
            "Stronger small-footprint STEM and code reasoning.",
            10,
            12,
            false),
        CatalogModel(
            "smollm2:135m",
            "SmolLM2 135M",
            "Oct 2024",
            "",
            "~271 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "8K",
            "4K safe",
            FourKSourceBudget,
            "Extremely fast",
            "Tiny local classification and smoke-test model.",
            0,
            1,
            true),
        CatalogModel(
            "smollm2:360m",
            "SmolLM2 360M",
            "Oct 2024",
            "",
            "~726 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "8K",
            "4K safe",
            FourKSourceBudget,
            "Very fast",
            "Tiny summaries and cheap on-device experiments.",
            0,
            1,
            true),
        CatalogModel(
            "smollm2:1.7b",
            "SmolLM2 1.7B",
            "Oct 2024",
            "",
            "~1.8 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "8K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Small local chat and summaries when footprint matters.",
            0,
            2,
            true),
        CatalogModel(
            "starcoder2:3b",
            "StarCoder2 3B",
            "Feb 2024",
            "",
            "~1.7 GB Q4",
            "BigCode OpenRAIL-M",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "16K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast code model",
            "Transparent code model baseline for small coding tasks.",
            3.5,
            4,
            true),
        CatalogModel(
            "starcoder2:7b",
            "StarCoder2 7B",
            "Feb 2024",
            "",
            "~4.0 GB Q4",
            "BigCode OpenRAIL-M",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "16K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Open code model baseline for patch review and completion-style tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "starcoder2:15b",
            "StarCoder2 15B",
            "Feb 2024",
            "",
            "~9.1 GB Q4",
            "BigCode OpenRAIL-M",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "16K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Larger transparent code model for careful local code analysis.",
            12,
            16,
            false),
        CatalogModel(
            "exaone3.5:2.4b",
            "EXAONE 3.5 2.4B",
            "Dec 2024",
            "",
            "~1.6 GB Q4",
            "EXAONE AI Model License",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small bilingual model",
            "English/Korean local chat, summaries, and review.",
            3.5,
            4,
            true),
        CatalogModel(
            "exaone3.5:7.8b",
            "EXAONE 3.5 7.8B",
            "Dec 2024",
            "",
            "~4.8 GB Q4",
            "EXAONE AI Model License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Bilingual English/Korean review and long-context chat.",
            6.5,
            8,
            false),
        CatalogModel(
            "exaone3.5:32b",
            "EXAONE 3.5 32B",
            "Dec 2024",
            "",
            "~19 GB Q4",
            "EXAONE AI Model License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large bilingual model",
            "Higher-depth bilingual English/Korean analysis on large local machines.",
            20,
            24,
            false),
        CatalogModel(
            "minicpm-v:8b",
            "MiniCPM-V 2.6 8B",
            "Aug 2024",
            "",
            "~5.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Efficient vision-language model",
            "OCR, screenshots, image understanding, and compact multimodal review.",
            6.5,
            8,
            false),

    ];
}
