// CC-DESC: Image-generation local LLM catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> ImageGenerationCatalog { get; } =
    [
        CatalogModel(
            "runwayml/stable-diffusion-v1-5",
            "Stable Diffusion 1.5",
            "Aug 2022",
            StabilityIconSource,
            "~4.3 GB FP16",
            "CreativeML Open RAIL-M",
            "4 GB VRAM with low-VRAM/offload; 8 GB RAM",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Best-supported 4 GB VRAM image baseline",
            "512x512 text-to-image, image-to-image, inpainting, LoRA experiments, and broad community checkpoint compatibility.",
            4,
            6,
            true),
        CatalogModel(
            "stabilityai/stable-diffusion-2-1-base",
            "Stable Diffusion 2.1 Base 512",
            "Dec 2022",
            StabilityIconSource,
            "~5.2 GB FP16",
            "CreativeML Open RAIL++-M",
            "4-6 GB VRAM with attention slicing/offload",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "512px SD2 baseline for modest GPUs",
            "Text-to-image at 512x512 when SD2 aesthetics or OpenCLIP prompting are preferred over SD1.5 ecosystem breadth.",
            4.5,
            6,
            true),
        CatalogModel(
            "segmind/tiny-sd",
            "Tiny Stable Diffusion",
            "2023",
            HuggingFaceIconSource,
            "~1.2 GB FP16",
            "Apache 2.0",
            "2 GB VRAM or CPU fallback",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Tiny low-memory diffusion smoke-test model",
            "Very small text-to-image experiments, dependency checks, and CPU/old-GPU validation where quality is secondary.",
            2,
            4,
            true),
        CatalogModel(
            "nota-ai/bk-sdm-small",
            "BK-SDM Small",
            "2023",
            HuggingFaceIconSource,
            "~1.7 GB FP16",
            "CreativeML Open RAIL-M",
            "2-4 GB VRAM; CPU fallback possible",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Compressed SD1.4/1.5-style generator",
            "Fast low-memory 512px drafts and iteration on hardware below the normal SD1.5 comfort range.",
            2.5,
            4,
            true),
        CatalogModel(
            "SimianLuo/LCM_Dreamshaper_v7",
            "LCM DreamShaper v7",
            "Oct 2023",
            StabilityIconSource,
            "~2.1 GB FP16",
            "CreativeML Open RAIL-M",
            "4 GB VRAM; 4-8 inference steps",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Fast SD1.5-derived low-step image model",
            "Quick concept art and illustration drafts on 4 GB GPUs using latent consistency sampling.",
            4,
            6,
            true),
        CatalogModel(
            "stabilityai/sd-turbo",
            "SD Turbo",
            "Nov 2023",
            StabilityIconSource,
            "~2.8 GB FP16",
            "Stability AI Non-Commercial Research Community License",
            "4 GB VRAM; 1-4 inference steps",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Very fast distilled SD image model",
            "Near-realtime low-step 512px drafts where speed matters more than maximum prompt fidelity.",
            4,
            6,
            true),
        CatalogModel(
            "segmind/SSD-1B",
            "SSD-1B",
            "Oct 2023",
            StabilityIconSource,
            "~4.7 GB FP16",
            "Apache 2.0",
            "6 GB VRAM minimum; lower with CPU offload",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Compact SDXL-style 1024px model",
            "Higher-resolution drafts than SD1.5 on mid-low hardware; may need offload on strict 4 GB cards.",
            6,
            8,
            true),
        CatalogModel(
            "x/flux1-schnell-q2",
            "FLUX.1 Schnell Q2 GGUF",
            "Aug 2024",
            BlackForestIconSource,
            "~4-6 GB quantized",
            "Apache 2.0",
            "4 GB VRAM with GGUF offload; 16-32 GB system RAM",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Quantized FLUX route for very tight GPUs",
            "Modern prompt-following image generation through stable-diffusion.cpp or ComfyUI GGUF workflows; slower than SD1.5.",
            4,
            8,
            true),
        CatalogModel(
            "x/flux1-dev-q4",
            "FLUX.1 Dev Q4 GGUF",
            "Aug 2024",
            BlackForestIconSource,
            "~8-12 GB quantized",
            "FLUX.1 Dev Non-Commercial License",
            "4-6 GB VRAM with heavy offload; 32 GB system RAM advised",
            "-",
            ImageGenContext,
            ImageGenBudget,
            "Higher-quality quantized FLUX route",
            "Better prompt fidelity than Schnell, but slow on 4 GB cards and best treated as an experimental low-hardware option.",
            4,
            12,
            true),
        CatalogModel(
            "black-forest-labs/FLUX.2-klein-4B",
            "FLUX.2 Klein 4B Diffusers",
            "Jan 2026",
            BlackForestIconSource,
            "~15-16 GB Diffusers cache; 13 GB VRAM target",
            "Apache 2.0",
            "8 GB VRAM with CPU offload; 13 GB VRAM recommended",
            "-",
            "Prompt-only image generation",
            "Prompt-only image generation; no chat context window.",
            "Windows-capable FLUX.2 route through Diffusers",
            "Generate images, UI mockups, product shots, and readable text layouts through Hugging Face Diffusers on Windows/Linux/macOS. Slower than Ollama's macOS image runner on 8 GB GPUs because it relies on CPU offload.",
            8,
            13,
            false),
        CatalogModel(
            "x/flux2-klein",
            "FLUX.2 Klein 4B",
            "Jan 2026",
            "",
            "5.7 GB",
            "Apache 2.0",
            "macOS Ollama image runtime; 8 GB+ unified memory advised",
            "-",
            "Prompt-only image generation",
            "Prompt-only image generation; no chat context window.",
            "Mac-only experimental Ollama image model",
            "Generate images, UI mockups, product shots, and readable text layouts from prompts on macOS; disabled on Windows/Linux until Ollama image support arrives there.",
            8,
            12,
            false),
        CatalogModel(
            "x/flux2-klein:9b",
            "FLUX.2 Klein 9B",
            "Jan 2026",
            "",
            "12 GB",
            "FLUX Non-Commercial License v2.1",
            "macOS Ollama image runtime; 16 GB+ unified memory advised",
            "-",
            "Prompt-only image generation",
            "Prompt-only image generation; no chat context window.",
            "Mac-only experimental Ollama image model",
            "Generate higher-quality images, typography-heavy mockups, product shots, and visual concepts from prompts on macOS; disabled on Windows/Linux until Ollama image support arrives there.",
            16,
            24,
            false),
        CatalogModel(
            "x/z-image-turbo",
            "Z-Image Turbo FP8",
            "Jan 2026",
            "",
            "13 GB",
            "Apache 2.0",
            "macOS Ollama image runtime; 16 GB+ unified memory advised",
            "-",
            "Prompt-only image generation",
            "Prompt-only image generation; no chat context window.",
            "Mac-only experimental Ollama image model",
            "Generate photorealistic images, portraits, scenes, and bilingual text-in-image compositions from prompts on macOS; disabled on Windows/Linux until Ollama image support arrives there.",
            16,
            24,
            false),
    ];
}
