// CC-DESC: Qwen modern and vision catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> QwenModernCatalog { get; } =
    [
        CatalogModel(
            "qwen3.5:0.8b",
            "Qwen3.5 0.8B",
            "Mar 2026",
            QwenIconSource,
            "~1.0 GB Q8",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "256K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Very fast on CPU or small GPUs",
            "Newest tiny Qwen multimodal/tool baseline for routing, summaries, and quick chat.",
            0,
            1.5,
            true),
        CatalogModel(
            "qwen3.5:2b-q4_K_M",
            "Qwen3.5 2B Q4",
            "Mar 2026",
            QwenIconSource,
            "~1.9 GB Q4",
            "Apache 2.0",
            "6 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast on 4 GB VRAM",
            "Newer Qwen small model for CC scouting, multilingual chat, image-aware notes, and compact tool use.",
            3,
            4,
            true),
        CatalogModel(
            "qwen3.5:4b-q4_K_M",
            "Qwen3.5 4B Q4",
            "Mar 2026",
            QwenIconSource,
            "~3.4 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe; 8K if memory leaves room",
            FourKSourceBudget,
            "Likely the strongest 4 GB-class Qwen option",
            "Small patch review, richer chat, and multimodal/tool tasks when 2B models feel too shallow.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen3.5:9b",
            "Qwen3.5 9B",
            "Mar 2026",
            QwenIconSource,
            "~6.6 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "256K",
            "8K on 8 GB+; 16K if memory leaves room",
            EightKSourceBudget,
            "Strong mid-size multimodal Qwen",
            "Better coding, visual notes, and general chat than the tiny Qwen3.5 models on consumer GPUs.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen3.5:27b",
            "Qwen3.5 27B",
            "Mar 2026",
            QwenIconSource,
            "~17 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation multimodal reasoning model",
            "Large local Qwen option for multi-file review, agent planning, image-grounded notes, and longer CC sessions.",
            18,
            24,
            false),
        CatalogModel(
            "qwen3.5:35b",
            "Qwen3.5 35B-A3B",
            "Mar 2026",
            QwenIconSource,
            "~24 GB Q4",
            "Apache 2.0",
            "64 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Sparse Qwen workstation model",
            "Agentic coding, multimodal review, and long-running project analysis when local memory is generous.",
            22,
            24,
            false),
        CatalogModel(
            "qwen3.5:122b",
            "Qwen3.5 122B-A10B",
            "Mar 2026",
            QwenIconSource,
            "~81 GB Q4",
            "Apache 2.0",
            "128 GB+ RAM; multi-GPU/server preferred",
            "256K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Server-class Qwen multimodal model",
            "High-end local/server Qwen for large reviews, agent scaffolds, and heavier reasoning.",
            80,
            96,
            false),
        CatalogModel(
            "qwen3.5:397b-cloud",
            "Qwen3.5 397B Cloud",
            "Mar 2026",
            QwenIconSource,
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud-hosted frontier Qwen",
            "Use when you want the strongest Qwen3.5 route without local server-class hardware.",
            0,
            0,
            true),
        CatalogModel(
            "qwen3.6:27b",
            "Qwen3.6 27B",
            "Apr 2026",
            QwenIconSource,
            "~17 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Newer Qwen agentic coding model",
            "Repository-level reasoning, frontend/code workflows, and thinking-preserving long chats.",
            18,
            24,
            false),
        CatalogModel(
            "qwen3.6:35b",
            "Qwen3.6 35B-A3B",
            "Apr 2026",
            QwenIconSource,
            "~24 GB Q4",
            "Apache 2.0",
            "64 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Newest sparse Qwen coding model",
            "High-end local Qwen for agentic coding, iterative project work, and multimodal reasoning.",
            22,
            24,
            false),
        CatalogModel(
            "qwen3.5:cloud",
            "Qwen3.5 Cloud",
            "Mar 2026",
            QwenIconSource,
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud Qwen multimodal route",
            "Default cloud Qwen3.5 endpoint for strong multilingual chat, vision, coding, and agentic workflows.",
            0,
            0,
            true),
        CatalogModel(
            "qwen3-coder-next:cloud",
            "Qwen3 Coder Next Cloud",
            "Sep 2025",
            QwenIconSource,
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "256K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud coding MoE model",
            "Large Qwen agentic coding route for repository-scale work without a local 52 GB download.",
            0,
            0,
            true),
        CatalogModel(
            "qwen2.5:0.5b",
            "Qwen2.5 0.5B",
            "Sep 2024",
            QwenIconSource,
            "~398 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny CPU-friendly multilingual model",
            "Very cheap routing, summaries, and English/Chinese chat smoke tests.",
            0,
            1,
            true),
        CatalogModel(
            "qwen2.5:1.5b",
            "Qwen2.5 1.5B",
            "Sep 2024",
            QwenIconSource,
            "~986 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Fast small multilingual model",
            "Low-memory English/Chinese assistant work, extraction, and lightweight draft generation.",
            0,
            2,
            true),
        CatalogModel(
            "qwen2.5:3b",
            "Qwen2.5 3B",
            "Sep 2024",
            QwenIconSource,
            "~1.9 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good 4 GB-class multilingual chat model",
            "Small assistant model with better reasoning and language coverage than sub-2B options.",
            3,
            4,
            true),
        CatalogModel(
            "qwen2.5:7b",
            "Qwen2.5 7B",
            "Sep 2024",
            QwenIconSource,
            "~4.7 GB Q4",
            "Apache 2.0",
            "12 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Classic balanced Qwen chat model",
            "Reliable multilingual chat, coding help, summaries, and tool-style assistant work.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen2.5:14b",
            "Qwen2.5 14B",
            "Sep 2024",
            QwenIconSource,
            "~9.0 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "32K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Stronger mid-size Qwen chat model",
            "Higher-quality English/Chinese chat, code review, and reasoning when 7B is too shallow.",
            10,
            12,
            false),
        CatalogModel(
            "qwen2.5:32b",
            "Qwen2.5 32B",
            "Sep 2024",
            QwenIconSource,
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Qwen2.5 instruct model",
            "Still-useful high-memory baseline for multilingual chat, code, and long review sessions.",
            20,
            24,
            false),
        CatalogModel(
            "qwen2.5:72b",
            "Qwen2.5 72B",
            "Sep 2024",
            QwenIconSource,
            "~47 GB Q4",
            "Apache 2.0",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "32K",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Large classic Qwen instruct model",
            "Server-class Qwen2.5 route for stronger multilingual chat, coding, and reasoning comparisons.",
            48,
            64,
            false),
        CatalogModel(
            "qwen2.5vl:3b",
            "Qwen2.5-VL 3B",
            "Jan 2025",
            QwenIconSource,
            "~3.2 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "125K",
            "4K safe; 8K if memory leaves room",
            FourKSourceBudget,
            "Small Qwen vision-language model",
            "Image-aware chat, screenshots, OCR-like notes, and visual issue triage on modest hardware.",
            3.5,
            4,
            true),
        CatalogModel(
            "qwen2.5vl:7b",
            "Qwen2.5-VL 7B",
            "Jan 2025",
            QwenIconSource,
            "~6.0 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "125K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Balanced Qwen vision-language model",
            "Better image-grounded assistant work, OCR, UI review, and multimodal summaries than the 3B variant.",
            6.5,
            8,
            false),
        CatalogModel(
            "qwen2.5vl:32b",
            "Qwen2.5-VL 32B",
            "Jan 2025",
            QwenIconSource,
            "~21 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "125K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Qwen vision-language model",
            "High-memory Qwen route for screenshots, documents, UI analysis, and multimodal coding notes.",
            20,
            24,
            false),
        CatalogModel(
            "qwen2.5vl:72b",
            "Qwen2.5-VL 72B",
            "Jan 2025",
            QwenIconSource,
            "~49 GB Q4",
            "Apache 2.0",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "125K",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Server-class Qwen vision-language model",
            "Large multimodal Qwen baseline for image-heavy analysis, documents, UI review, and visual reasoning.",
            48,
            64,
            false),
        CatalogModel(
            "qwq:32b",
            "QwQ 32B",
            "Mar 2025",
            QwenIconSource,
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Qwen reasoning model",
            "Reasoning-focused Qwen option for math, code critique, and careful multi-step decisions.",
            20,
            24,
            false),

    ];
}
