// CC-DESC: Gemma and DeepSeek local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaGemmaDeepSeekCatalog { get; } =
    [
        CatalogModel(
            "gemma3:270m",
            "Gemma 3 270M",
            "Mar 12, 2025",
            "",
            "~292 MB Q4",
            "Gemma Terms of Use",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny and very fast",
            "Micro summaries, classification, and cheap local experiments.",
            0,
            1,
            true),
        CatalogModel(
            "gemma3:1b",
            "Gemma 3 1B",
            "Mar 12, 2025",
            "",
            "~815 MB Q4",
            "Gemma Terms of Use",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Small general chat, summaries, and constrained local tasks.",
            0,
            2,
            true),
        CatalogModel(
            "gemma3:4b",
            "Gemma 3 4B",
            "Mar 12, 2025",
            "",
            "~3.3 GB Q4",
            "Gemma Terms of Use",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "Compact multimodal general chat and review.",
            3.5,
            4,
            true),
        CatalogModel(
            "gemma3:12b",
            "Gemma 3 12B",
            "Mar 12, 2025",
            "",
            "~8.1 GB Q4",
            "Gemma Terms of Use",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "128K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Richer multimodal chat and reasoning on larger local machines.",
            10,
            16,
            false),
        CatalogModel(
            "gemma3:27b",
            "Gemma 3 27B",
            "Mar 12, 2025",
            "",
            "~17 GB Q4",
            "Gemma Terms of Use",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large single-GPU-class model",
            "Strong Gemma-family reasoning and multimodal review on high-memory machines.",
            20,
            24,
            false),

        CatalogModel(
            "deepseek-r1:1.5b",
            "DeepSeek R1 Distill Qwen 1.5B",
            "Jan 20, 2025",
            "",
            "~1.1 GB Q4",
            "MIT",
            "4 GB RAM; CPU works",
            "128K",
            "4K safe",
            FourKSourceBudget,
            "Fast reasoning sampler",
            "Small reasoning checks and critique passes.",
            0,
            2,
            true),
        CatalogModel(
            "deepseek-r1:7b",
            "DeepSeek R1 Distill Qwen 7B",
            "Jan 20, 2025",
            "",
            "~4.7 GB Q4",
            "MIT",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Reasoning-focused review and planning on midrange GPUs.",
            6.5,
            8,
            false),
        CatalogModel(
            "deepseek-r1:8b",
            "DeepSeek R1 0528 Qwen3 8B",
            "May 28, 2025",
            "",
            "~5.2 GB Q4",
            "MIT",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Newer small reasoning model for planning and bug analysis.",
            6.5,
            8,
            false),
        CatalogModel(
            "deepseek-r1:14b",
            "DeepSeek R1 Distill Qwen 14B",
            "Jan 20, 2025",
            "",
            "~9.0 GB Q4",
            "MIT",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "128K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Reasoning-heavy analysis when small models miss multi-step issues.",
            12,
            16,
            false),
        CatalogModel(
            "deepseek-r1:32b",
            "DeepSeek R1 Distill Qwen 32B",
            "Jan 20, 2025",
            "",
            "~20 GB Q4",
            "MIT",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class reasoning model",
            "Deep reasoning, planning, and consistency review.",
            20,
            24,
            false),
        CatalogModel(
            "deepseek-r1:70b",
            "DeepSeek R1 Distill Llama 70B",
            "Jan 20, 2025",
            "",
            "~43 GB Q4",
            "MIT; base Llama terms apply",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class reasoning model",
            "Large-model reasoning and critique when local hardware allows.",
            48,
            64,
            false),
        CatalogModel(
            "deepseek-r1:671b",
            "DeepSeek R1 0528 671B",
            "May 28, 2025",
            "",
            "~404 GB Q4",
            "MIT",
            "512 GB RAM; multi-GPU/server recommended",
            "160K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class reasoning model",
            "Top-end open reasoning experiments on specialized hardware.",
            384,
            512,
            false),

    ];
}
