// CC-DESC: Mistral-family and GPT-OSS local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaMistralOpenAiCatalog { get; } =
    [
        CatalogModel(
            "mistral-small3.2:24b",
            "Mistral Small 3.2 24B",
            "Jun 2025",
            "",
            "~15 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large local instruction model",
            "Tool-aware general reasoning and image/text review on high-memory machines.",
            20,
            24,
            false),
        CatalogModel(
            "devstral:24b",
            "Devstral 24B",
            "May 2025",
            "",
            "~14 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Agentic coding model",
            "Software engineering agent tasks, repo exploration, and patch planning.",
            20,
            24,
            false),
        CatalogModel(
            "magistral:24b",
            "Magistral 24B",
            "Jun 2025",
            "",
            "~14 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 24 GB+ VRAM recommended",
            "39K",
            "8K-16K; keep under 40K",
            EightKSourceBudget,
            "Reasoning model",
            "Transparent multi-step reasoning and planning when latency is acceptable.",
            20,
            24,
            false),
        CatalogModel(
            "codestral:22b",
            "Codestral 22B",
            "May 29, 2024",
            "",
            "~13 GB Q4",
            "Mistral AI Non-Production License",
            "32 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            EightKSourceBudget,
            "Large code model",
            "Code completion, explanation, and review where license terms fit your use.",
            18,
            24,
            false),

        CatalogModel(
            "gpt-oss:20b",
            "GPT-OSS 20B",
            "Aug 5, 2025",
            "",
            "~14 GB MXFP4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "128K",
            "8K-16K on 16 GB+",
            LargeSourceBudget,
            "OpenAI open-weight reasoning model",
            "Agentic coding, reasoning, structured outputs, and careful review.",
            14,
            16,
            false),
        CatalogModel(
            "gpt-oss:120b",
            "GPT-OSS 120B",
            "Aug 5, 2025",
            "",
            "~65 GB MXFP4",
            "Apache 2.0",
            "128 GB RAM; 80 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large OpenAI open-weight reasoning model",
            "Server/workstation-class reasoning and coding review.",
            64,
            80,
            false),
        CatalogModel(
            "gpt-oss:20b-cloud",
            "GPT-OSS 20B Cloud",
            "Aug 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "128K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud OpenAI open-weight reasoning model",
            "Use GPT-OSS 20B through Ollama Cloud for coding, reasoning, and structured assistant tasks.",
            0,
            0,
            true),
        CatalogModel(
            "gpt-oss:120b-cloud",
            "GPT-OSS 120B Cloud",
            "Aug 2025",
            "",
            "Ollama Cloud",
            "Apache 2.0",
            "Ollama account/cloud access; no local VRAM",
            "128K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud large OpenAI open-weight model",
            "Run GPT-OSS 120B via cloud for high-reasoning assistant and code-review workflows.",
            0,
            0,
            true),

    ];
}
