// CC-DESC: Phi, Granite, and Command-R local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaPhiGraniteCohereCatalog { get; } =
    [
        CatalogModel(
            "phi4-mini",
            "Phi-4 Mini 3.8B",
            "Feb 26, 2025",
            PhiIconSource,
            "~2.5 GB Q4",
            "MIT",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Medium on 4 GB VRAM",
            "Refactor planning, reasoning, consistency review, project-style explanation.",
            3.5,
            4,
            true),
        CatalogModel(
            "phi4:14b",
            "Phi-4 14B",
            "Dec 12, 2024",
            PhiIconSource,
            "~9.1 GB Q4",
            "MIT",
            "24 GB RAM; 16 GB+ VRAM recommended",
            "16K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Stronger general reasoning, math, and consistency checks.",
            12,
            16,
            false),
        CatalogModel(
            "phi4-mini-reasoning",
            "Phi-4 Mini Reasoning 3.8B",
            "Apr 30, 2025",
            PhiIconSource,
            "~3.2 GB Q4",
            "MIT",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Medium on 4 GB VRAM",
            "Small reasoning model for planning, critiques, and step-by-step review.",
            3.5,
            4,
            true),
        CatalogModel(
            "phi4-reasoning:14b",
            "Phi-4 Reasoning 14B",
            "Apr 30, 2025",
            PhiIconSource,
            "~11 GB Q4",
            "MIT",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Deliberate reasoning and review when latency matters less than depth.",
            14,
            16,
            false),
        CatalogModel(
            "phi4-reasoning:plus",
            "Phi-4 Reasoning Plus 14B",
            "Apr 30, 2025",
            PhiIconSource,
            "~11 GB Q4",
            "MIT",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K safe on 16 GB+",
            EightKSourceBudget,
            "Heavy on consumer GPUs",
            "Higher-reasoning Phi option for careful review and planning passes.",
            14,
            16,
            false),

        CatalogModel(
            "granite-code:3b",
            "Granite Code 3B",
            "May 6, 2024",
            GraniteIconSource,
            "~2.0 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Medium on 4 GB VRAM",
            "Code explanation and fixing alternative; useful against Qwen Coder.",
            3.5,
            4,
            true),
        CatalogModel(
            "granite-code:8b",
            "Granite Code 8B",
            "May 6, 2024",
            GraniteIconSource,
            "~4.6 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Code explanation, migration review, and medium patch authoring.",
            6.5,
            8,
            false),
        CatalogModel(
            "granite-code:20b",
            "Granite Code 20B",
            "May 6, 2024",
            GraniteIconSource,
            "~12 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 20 GB+ VRAM recommended",
            "8K",
            "8K on large GPUs",
            EightKSourceBudget,
            "Workstation-class local model",
            "Larger code reasoning when the 8B model is not deep enough.",
            18,
            20,
            false),
        CatalogModel(
            "granite-code:34b",
            "Granite Code 34B",
            "May 6, 2024",
            GraniteIconSource,
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 32 GB+ VRAM recommended",
            "8K",
            "8K on large GPUs",
            EightKSourceBudget,
            "Workstation-class local model",
            "Deep code review and architectural reasoning on high-memory machines.",
            24,
            32,
            false),

        CatalogModel(
            "granite3-dense:2b",
            "Granite 3 Dense 2B",
            "Oct 21, 2024",
            GraniteIconSource,
            "~1.6 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "4K",
            "4K safe",
            "4K: 150-300 LOC / 8k-12k chars.",
            "Fast CPU/small GPU model",
            "General local chat, summaries, and constrained review.",
            0,
            2,
            true),
        CatalogModel(
            "granite3-dense:8b",
            "Granite 3 Dense 8B",
            "Oct 21, 2024",
            GraniteIconSource,
            "~4.9 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "4K",
            "4K safe",
            "4K: 150-300 LOC / 8k-12k chars.",
            "Good on 8 GB+ GPUs",
            "General assistant work and concise project review.",
            6.5,
            8,
            false),
        CatalogModel(
            "granite3.1-dense:2b",
            "Granite 3.1 Dense 2B",
            "Dec 18, 2024",
            GraniteIconSource,
            "~1.6 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Lightweight general chat with a much larger advertised context window.",
            0,
            2,
            true),
        CatalogModel(
            "granite3.1-dense:8b",
            "Granite 3.1 Dense 8B",
            "Dec 18, 2024",
            GraniteIconSource,
            "~5.0 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Longer-context general assistant work and review passes.",
            6.5,
            8,
            false),
        CatalogModel(
            "granite3.2:2b",
            "Granite 3.2 2B",
            "Feb 26, 2025",
            GraniteIconSource,
            "~1.5 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Small reasoning-style assistant for summaries, planning, and chat.",
            0,
            2,
            true),
        CatalogModel(
            "granite3.2:8b",
            "Granite 3.2 8B",
            "Feb 26, 2025",
            GraniteIconSource,
            "~4.9 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Reasoning-style general assistant for review and planning.",
            6.5,
            8,
            false),
        CatalogModel(
            "granite3.3:2b",
            "Granite 3.3 2B",
            "Apr 30, 2025",
            GraniteIconSource,
            "~1.5 GB Q4",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Fast CPU/small GPU model",
            "Updated Granite 3 local assistant for chat, planning, and summaries.",
            0,
            2,
            true),
        CatalogModel(
            "granite3.3:8b",
            "Granite 3.3 8B",
            "Apr 30, 2025",
            GraniteIconSource,
            "~4.9 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Good on 8 GB+ GPUs",
            "Updated Granite 3 review, planning, and general chat option.",
            6.5,
            8,
            false),

        CatalogModel(
            "command-r:35b",
            "Command R 35B",
            "Aug 2024",
            "",
            "~19 GB Q4",
            "C4AI License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Cohere long-context RAG/tool model",
            "Conversational RAG, tool use, citations, and long-document assistant workflows.",
            18,
            24,
            false),
        CatalogModel(
            "command-r7b:7b",
            "Command R7B",
            "Dec 2024",
            "",
            "~5.1 GB Q4",
            "C4AI License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Compact Cohere R-series model",
            "Fast RAG/tool-style chat on ordinary GPUs with better latency than Command R.",
            6.5,
            8,
            false),
    ];
}
