// CC-DESC: Hugging Face GGUF catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> HuggingFaceGgufCatalog { get; } =
    [
        CatalogModel(
            "hf.co/bartowski/zai-org_GLM-4.5-Air-GGUF:Q4_K_M",
            "GLM-4.5 Air Q4",
            "Jul 2025",
            "",
            "~60 GB Q4",
            "Z.ai License",
            "96 GB+ RAM; multi-GPU/server preferred",
            "128K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large GLM MoE open-weight model",
            "Heavy local/server Z.ai route for agentic coding, reasoning, and multilingual chat.",
            48,
            64,
            false),
        CatalogModel(
            "hf.co/MaziyarPanahi/solar-pro-preview-instruct-GGUF:Q4_K_M",
            "Solar Pro Preview Instruct Q4",
            "Nov 2024",
            "",
            "~14 GB Q4",
            "Upstage License",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "64K",
            "8K on 16 GB+",
            EightKSourceBudget,
            "Korean/English capable instruct model",
            "Korea coverage for English-capable chat, reasoning, and general assistant work.",
            12,
            16,
            false),
        CatalogModel(
            "hf.co/QuantFactory/SeaLLMs-v3-7B-Chat-GGUF:Q4_K_M",
            "SeaLLMs v3 7B Chat Q4",
            "Jun 2024",
            "",
            "~4.4 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Southeast Asia multilingual chat",
            "SEA-language plus English route for chat, translation-adjacent work, and summaries.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-0.5B-Instruct-GGUF:Q4_K_M",
            "Falcon H1 0.5B Instruct Q4",
            "May 21, 2025",
            "",
            "~335 MB Q4",
            "Falcon LLM License",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny hybrid reasoning/code model",
            "Niche ultra-small English-capable coding, reasoning, and instruction-following baseline.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-1.5B-Instruct-GGUF:Q4_K_M",
            "Falcon H1 1.5B Instruct Q4",
            "May 21, 2025",
            "",
            "~1.0 GB Q4",
            "Falcon LLM License",
            "4-6 GB RAM; CPU works; 2 GB+ VRAM comfortable",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small hybrid instruction model",
            "Low-memory coding notes, patch critique, summaries, and reasoning experiments.",
            0,
            2,
            true),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-1.5B-Deep-Instruct-GGUF:Q4_K_M",
            "Falcon H1 1.5B Deep Q4",
            "May 21, 2025",
            "",
            "~994 MB Q4",
            "Falcon LLM License",
            "4-6 GB RAM; CPU works; 2 GB+ VRAM comfortable",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Deeper small hybrid model",
            "Niche reasoning-heavy small model for code critique, math-ish checks, and compact local chat.",
            0,
            2,
            true),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-3B-Instruct-GGUF:Q4_K_M",
            "Falcon H1 3B Instruct Q4",
            "May 21, 2025",
            "",
            "~2.01 GB Q4",
            "Falcon LLM License",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "4 GB-class hybrid instruction model",
            "Interesting 3B alternative for code discussion, patch critique, and long-context small-model experiments.",
            3,
            4,
            true),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-7B-Instruct-GGUF:Q4_K_M",
            "Falcon H1 7B Instruct Q4",
            "May 2025",
            "",
            "~4.5 GB Q4",
            "TII Falcon License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "UAE hybrid instruct model",
            "Middle East coverage for English-capable chat, summaries, and compact coding tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/tiiuae/Falcon-H1-34B-Instruct-GGUF:Q4_K_M",
            "Falcon H1 34B Instruct Q4",
            "May 2025",
            "",
            "~20 GB Q4",
            "TII Falcon License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large UAE hybrid instruct model",
            "Bigger Falcon H1 route for multilingual chat, code, and reasoning on workstation hardware.",
            20,
            24,
            false),
        CatalogModel(
            "hf.co/bartowski/aya-expanse-8b-GGUF:Q4_K_M",
            "Aya Expanse 8B Q4",
            "Oct 2024",
            "",
            "~4.8 GB Q4",
            "C4AI License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Multilingual open chat model",
            "Broad language coverage with English support for chat, summaries, and global user workflows.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/bartowski/c4ai-command-r7b-12-2024-GGUF:Q4_K_M",
            "Command R7B 12-2024 Q4",
            "Dec 2024",
            "",
            "~4.5 GB Q4",
            "C4AI License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "RAG/tool chat model",
            "Compact Command-R route for retrieval-style chat, tool use, and long-context assistant work.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/MaziyarPanahi/Mistral-Nemo-Instruct-2407-GGUF:Q4_K_M",
            "Mistral Nemo 12B Instruct Q4",
            "Jul 2024",
            "",
            "~7.5 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Efficient Mistral multilingual instruct",
            "Good European open model baseline for coding, chat, RAG, and global language support.",
            10,
            12,
            false),
        CatalogModel(
            "hf.co/MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-GGUF:Q4_K_M",
            "Mixtral 8x22B Instruct Q4",
            "Apr 2024",
            "",
            "~80 GB Q4",
            "Apache 2.0",
            "128 GB+ RAM; multi-GPU/server preferred",
            "64K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large classic Mistral MoE",
            "Still useful server-class open MoE for code, multilingual chat, and deep reviews.",
            64,
            80,
            false),
        CatalogModel(
            "hf.co/NousResearch/Hermes-3-Llama-3.1-8B-GGUF:Q4_K_M",
            "Hermes 3 Llama 3.1 8B Q4",
            "Aug 2024",
            "",
            "~4.9 GB Q4",
            "Llama 3.1 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "General assistant fine-tune",
            "Instruction-following chat, structured output, role-play-safe assistant work, and light coding.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/mradermacher/AI21-Jamba-Mini-1.5-GGUF:Q4_K_M",
            "Jamba 1.5 Mini Q4",
            "Aug 2024",
            "",
            "~22 GB Q4",
            "AI21 Open Model License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "256K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Hybrid SSM/Transformer long-context model",
            "Long-context chat, document analysis, and RAG-style assistant work on roomy machines.",
            20,
            24,
            false),
        CatalogModel(
            "hf.co/allenai/OLMo-2-0325-32B-Instruct-GGUF:Q4_K_S",
            "OLMo 2 32B Instruct Q4_K_S",
            "Mar 2025",
            "",
            "~19 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "4K",
            "4K-8K on large GPUs",
            LargeSourceBudget,
            "Open science 32B instruct model",
            "Transparent model lineage for high-memory chat, evaluation, and coding/review tasks.",
            18,
            24,
            false),
        CatalogModel(
            "hf.co/bartowski/OpenThinker-7B-GGUF:Q4_K_M",
            "OpenThinker 7B Q4",
            "Feb 2025",
            "",
            "~4.4 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Compact reasoning model",
            "Small open reasoning route for math, checklists, patch critique, and structured decisions.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/unsloth/Apertus-8B-Instruct-2509-GGUF:Q4_K_M",
            "Apertus 8B Instruct Q4",
            "Sep 2025",
            "",
            "~4.8 GB Q4",
            "Apertus Open Model License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K+",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Swiss fully open multilingual model",
            "Global coverage with open weights/data/training details for English-capable multilingual chat.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/unsloth/Apertus-70B-Instruct-2509-GGUF:Q4_K_M",
            "Apertus 70B Instruct Q4",
            "Sep 2025",
            "",
            "~43 GB Q4",
            "Apertus Open Model License",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "32K+",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Large Swiss fully open multilingual model",
            "Server-class fully open model for multilingual chat, code/math comparisons, and transparent audits.",
            48,
            64,
            false),
        CatalogModel(
            "hf.co/aisingapore/Llama-SEA-LION-v3-8B-IT-GGUF:Q4_K_M",
            "SEA-LION v3 8B IT Q4",
            "Sep 2024",
            "",
            "~4.8 GB Q4",
            "Llama 3 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Singapore/Southeast Asia instruct model",
            "English plus Southeast Asian language coverage for regional chat, summaries, and localization.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/mradermacher/LLaMA-3-MERaLiON-8B-Instruct-GGUF:Q4_K_M",
            "MERaLiON Llama 3 8B Instruct Q4",
            "Jan 2025",
            "",
            "~4.8 GB Q4",
            "Llama 3 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Singapore multilingual instruct model",
            "English, Chinese, Indonesian, Malay, and Singlish-oriented assistant coverage.",
            6.5,
            8,
            false),
        CatalogModel(
            "sailor2:1b",
            "Sailor2 1B",
            "Dec 2024",
            "",
            "~739 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny Southeast Asia multilingual model",
            "SEA-language plus English chat, routing, and low-memory localization experiments.",
            0,
            1.5,
            true),
        CatalogModel(
            "sailor2:8b",
            "Sailor2 8B",
            "Dec 2024",
            "",
            "~5.2 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Southeast Asia multilingual chat model",
            "Strong regional model for SEA languages while retaining English and Chinese capability.",
            6.5,
            8,
            false),
        CatalogModel(
            "sailor2:20b",
            "Sailor2 20B",
            "Dec 2024",
            "",
            "~12 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K on 16 GB+",
            EightKSourceBudget,
            "Large Southeast Asia multilingual chat model",
            "Higher-quality SEA multilingual and English/Chinese chat on workstation-class machines.",
            12,
            16,
            false),
        CatalogModel(
            "aya:8b",
            "Aya 23 8B",
            "May 2024",
            "",
            "~4.8 GB Q4",
            "CC-BY-NC",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Cohere multilingual chat model",
            "Compact Aya route for English-capable chat across 23 languages.",
            6.5,
            8,
            false),
        CatalogModel(
            "aya:35b",
            "Aya 23 35B",
            "May 2024",
            "",
            "~20 GB Q4",
            "CC-BY-NC",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "8K",
            "4K-8K on large GPUs",
            EightKSourceBudget,
            "Large Cohere multilingual chat model",
            "Higher-quality multilingual chat and translation-adjacent work across 23 languages.",
            20,
            24,
            false),
        CatalogModel(
            "aya-expanse:32b",
            "Aya Expanse 32B",
            "Oct 2024",
            "",
            "~19 GB Q4",
            "CC-BY-NC",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Cohere multilingual/RAG model",
            "Long-context multilingual assistant work, RAG-style chat, and global support coverage.",
            18,
            24,
            false),
        CatalogModel(
            "dbrx:132b",
            "DBRX 132B",
            "Mar 2024",
            "",
            "~75 GB Q4",
            "Databricks Open Model License",
            "128 GB+ RAM; multi-GPU/server preferred",
            "32K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Databricks open MoE model",
            "Large open enterprise MoE baseline for chat, code, and long-form analysis.",
            72,
            96,
            false),
        CatalogModel(
            "solar:10.7b",
            "Solar 10.7B",
            "Dec 2023",
            "",
            "~6.1 GB Q4",
            "Upstage License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "4K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Korean/English compact chat model",
            "Classic Solar route for Korean/English chat and single-turn assistant comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "command-r-plus:104b",
            "Command R+ 104B",
            "Apr 2024",
            "",
            "~59 GB Q4",
            "C4AI License",
            "128 GB+ RAM; multi-GPU/server preferred",
            "128K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large RAG/tool chat model",
            "Cohere route for enterprise RAG, tool use, citations, and long-context assistant workflows.",
            56,
            80,
            false),

        CatalogModel(
            "LiquidAI/lfm2.5-1.2b-instruct",
            "LFM2.5 1.2B Instruct",
            "Apr 2026",
            "",
            "~731 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works; mobile/NPU friendly",
            "125K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Extremely fast low-memory hybrid model",
            "Agentic utility, extraction, RAG, routing, and structured chat on very small hardware.",
            0,
            1,
            true),
        CatalogModel(
            "lfm2.5-thinking:1.2b",
            "LFM2.5 1.2B Thinking",
            "Jan 2026",
            "",
            "~731 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works; mobile/NPU friendly",
            "125K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Tiny reasoning model with low memory pressure",
            "Reasoning-lite checks, structured decisions, and patch critique when thinking is useful.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/LiquidAI/LFM2.5-350M-GGUF:Q4_K_M",
            "LFM2.5 350M Q4",
            "Mar 2026",
            "",
            "~230 MB Q4",
            "LFM 1.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny tool/extraction model",
            "New edge model for routing, extraction, structured output, and tool-call experiments; not a primary coding model.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/LiquidAI/LFM2-350M-GGUF:Q4_K_M",
            "LFM2 350M Q4",
            "Jul 2025",
            "",
            "~229 MB Q4",
            "LFM 1.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Ultra-tiny hybrid edge model",
            "Fast routing, summaries, extraction, and local assistant experiments when even 1B feels expensive.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/LiquidAI/LFM2-700M-GGUF:Q4_K_M",
            "LFM2 700M Q4",
            "Jul 2025",
            "",
            "~514 MB Q4",
            "LFM 1.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe",
            FourKSourceBudget,
            "Tiny hybrid edge model",
            "Fast English-capable chat, extraction, prompt compression, and simple coding notes.",
            0,
            1.5,
            true),
        CatalogModel(
            "hf.co/LiquidAI/LFM2-1.2B-GGUF:Q4_K_M",
            "LFM2 1.2B Q4",
            "Jul 2025",
            "",
            "~731 MB Q4",
            "LFM 1.0",
            "4 GB RAM; CPU works; 2 GB+ VRAM comfortable",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small hybrid edge model",
            "Low-memory chat, RAG utility, extraction, and simple code explanation experiments.",
            0,
            2,
            true),
        CatalogModel(
            "hf.co/LiquidAI/LFM2-2.6B-GGUF:Q4_K_M",
            "LFM2 2.6B Q4",
            "Sep 2025",
            "",
            "~1.56 GB Q4",
            "LFM 1.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "4 GB-class hybrid edge model",
            "Niche efficient alternative for chat, code explanation, RAG utility, and compact patch critique.",
            3,
            4,
            true),
        CatalogModel(
            "lfm2:24b",
            "LFM2 24B-A2B",
            "Feb 2026",
            "",
            "~14 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K on 16 GB+",
            EightKSourceBudget,
            "Efficient hybrid MoE model",
            "Liquid AI's larger on-device route for chat, tool use, and efficient code/document work.",
            12,
            16,
            false),
    ];
}
