// CC-DESC: Small and efficient model catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> SmallAndEfficientCatalog { get; } =
    [
        CatalogModel(
            "cogito:3b",
            "Cogito 3B",
            "Apr 2025",
            "",
            "~2.2 GB Q4",
            "Commercial-friendly open license; base terms apply",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small hybrid reasoning model",
            "Deep Cogito route for direct or reflective answers, coding, STEM, and multilingual chat.",
            3,
            4,
            true),
        CatalogModel(
            "cogito:8b",
            "Cogito 8B",
            "Apr 2025",
            "",
            "~4.9 GB Q4",
            "Commercial-friendly open license; base terms apply",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Balanced hybrid reasoning model",
            "Useful local reasoning/chat model with multilingual, coding, STEM, and tool-calling strength.",
            6.5,
            8,
            false),
        CatalogModel(
            "cogito:14b",
            "Cogito 14B",
            "Apr 2025",
            "",
            "~9.0 GB Q4",
            "Commercial-friendly open license; base terms apply",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Mid-size hybrid reasoning model",
            "Better Cogito route for coding, STEM, instruction following, and careful reflective answers.",
            10,
            12,
            false),
        CatalogModel(
            "cogito:32b",
            "Cogito 32B",
            "Apr 2025",
            "",
            "~20 GB Q4",
            "Commercial-friendly open license; base terms apply",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large hybrid reasoning model",
            "High-memory Cogito for code review, STEM reasoning, and longer reflective assistant tasks.",
            20,
            24,
            false),
        CatalogModel(
            "cogito:70b",
            "Cogito 70B",
            "Apr 2025",
            "",
            "~43 GB Q4",
            "Commercial-friendly open license; base terms apply",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Large hybrid reasoning model",
            "Server-class Cogito route for deep code, STEM, multilingual, and reflective reasoning work.",
            48,
            64,
            false),

        CatalogModel(
            "granite4:350m-h",
            "Granite 4.0 350M-H",
            "Oct 2, 2025",
            GraniteIconSource,
            "~366 MB Q8",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "1M",
            "4K safe",
            FourKSourceBudget,
            "Tiny hybrid Mamba-2 model",
            "Ultra-cheap classification, routing, extraction, and long-context experiments.",
            0,
            1,
            true),
        CatalogModel(
            "granite4:1b-h",
            "Granite 4.0 1B-H",
            "Oct 2, 2025",
            GraniteIconSource,
            "~1.6 GB Q8",
            "Apache 2.0",
            "4-6 GB RAM; CPU works",
            "1M",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small hybrid Mamba-2 model",
            "Fast enterprise-style extraction, summaries, and request routing with a huge advertised window.",
            0,
            2,
            true),
        CatalogModel(
            "granite4:3b",
            "Granite 4.0 3B Micro",
            "Oct 2, 2025",
            GraniteIconSource,
            "~2.1 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good 4 GB-class instruction model",
            "Newer Granite option for CC scouting, simple patches, function calling, and summaries.",
            3,
            4,
            true),
        CatalogModel(
            "granite4:3b-h",
            "Granite 4.0 3B-H Micro",
            "Oct 2, 2025",
            GraniteIconSource,
            "~1.9 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "1M",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Hybrid Mamba-2 model with lower footprint",
            "Best Granite 4 low-memory experiment for long-context routing and compact CC tasks.",
            3,
            4,
            true),

        CatalogModel(
            "hf.co/microsoft/bitnet-b1.58-2B-4T-gguf",
            "BitNet b1.58 2B4T",
            "Apr 2025",
            "",
            "~1.19 GB I2_S",
            "MIT",
            "CPU-first; 4 GB RAM works; no VRAM required",
            "4K",
            "4K only",
            "4K: 150-300 LOC / 8k-12k chars.",
            "1.58-bit CPU model; performance depends on recent llama.cpp/Ollama support",
            "Experimental ultra-low-memory chat and routing where CPU efficiency matters more than context.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/ggml-org/SmolLM3-3B-GGUF:Q4_K_M",
            "SmolLM3 3B Q4",
            "Jul 8, 2025",
            "",
            "~1.92 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Efficient open 3B reasoning/chat model",
            "Hybrid thinking/no-thinking small model for structured output, multilingual chat, and compact patch review.",
            3,
            4,
            true),
        CatalogModel(
            "smallthinker:3b-preview-q4_K_M",
            "SmallThinker 3B Q4",
            "Dec 2024",
            "",
            "~2.1 GB Q4",
            "Apache 2.0",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Small reasoning model",
            "Reasoning-lite checks and draft answers; suppress/strip thinking for CC patch blocks.",
            3,
            4,
            true),

        CatalogModel(
            "nemotron-3-nano:4b",
            "Nemotron 3 Nano 4B",
            "Mar 2026",
            "",
            "~2.8 GB Q4",
            "NVIDIA Open Model License",
            "8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe; 8K if memory leaves room",
            FourKSourceBudget,
            "Hybrid reasoning/tool model for the 4 GB class",
            "Agentic planning, tool-aware chat, and patch critique with reasoning suppressed for structured CC output.",
            3.5,
            4,
            true),
        CatalogModel(
            "ministral-3:3b",
            "Ministral 3 3B",
            "Dec 2025",
            "",
            "~3.0 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "256K",
            "4K safe; 8K if memory leaves room",
            FourKSourceBudget,
            "Edge vision/tool model",
            "Small multimodal chat, screenshot notes, tool use, and compact local assistant work.",
            3.5,
            4,
            true),

        CatalogModel(
            "gemma3n:e2b",
            "Gemma 3n E2B",
            "Jun 2025",
            "",
            "~5.6 GB Q4",
            "Gemma Terms of Use",
            "12 GB RAM; CPU fallback; above 4 GB VRAM in Ollama",
            "32K",
            "4K safe; avoid on 4 GB VRAM",
            FourKSourceBudget,
            "On-device architecture, but heavy Ollama package",
            "Selective-activation edge model for multilingual chat and code when memory allows.",
            5,
            6,
            false),
        CatalogModel(
            "gemma3n:e4b",
            "Gemma 3n E4B",
            "Jun 2025",
            "",
            "~7.5 GB Q4",
            "Gemma Terms of Use",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Stronger selective-activation edge model",
            "Larger Gemma 3n route for multilingual chat, summaries, and local assistant tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/LGAI-EXAONE/EXAONE-4.0-1.2B-GGUF:Q4_K_M",
            "EXAONE 4.0 1.2B Q4",
            "Jul 15, 2025",
            "",
            "~812 MB Q4",
            "EXAONE License",
            "4 GB RAM; CPU works",
            "64K",
            "4K safe, 8K usually okay",
            FourKSourceBudget,
            "Tiny hybrid reasoning/non-reasoning model",
            "On-device multilingual chat, RAG, and structured utility work with low memory cost.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/h2oai/h2o-danube3-500m-chat-GGUF:Q4_K_M",
            "H2O Danube3 500M Chat Q4",
            "Jul 17, 2024",
            "",
            "~318 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "8K",
            "4K safe",
            FourKSourceBudget,
            "Tiny CPU-friendly chat model",
            "Ultra-cheap local privacy, guardrail, routing, and short chat tasks.",
            0,
            1,
            true),
        CatalogModel(
            "hf.co/h2oai/h2o-danube3-4b-chat-GGUF:Q4_K_M",
            "H2O Danube3 4B Chat Q4",
            "Jul 17, 2024",
            "",
            "~2.39 GB Q4",
            "Apache 2.0",
            "8 GB RAM; 4 GB VRAM recommended",
            "8K",
            "4K safe",
            FourKSourceBudget,
            "Compact edge model trained on 6T tokens",
            "Small local chat, summaries, and request routing with better depth than sub-1B models.",
            3,
            4,
            true),

    ];
}
