// CC-DESC: Meta Llama local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaMetaCatalog { get; } =
    [
        CatalogModel(
            "llama3.1:8b",
            "Llama 3.1 8B",
            "Jul 23, 2024",
            "",
            "~4.7 GB Q4",
            "Llama 3.1 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Core Meta open model",
            "Widely supported baseline for general chat, coding, tool use, and long-context local workflows.",
            6.5,
            8,
            false),
        CatalogModel(
            "llama3.1:70b",
            "Llama 3.1 70B",
            "Jul 23, 2024",
            "",
            "~43 GB Q4",
            "Llama 3.1 Community License",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Meta open model",
            "High-memory Llama baseline for deep review, coding, and long-context reasoning.",
            40,
            64,
            false),
        CatalogModel(
            "llama3.1:405b",
            "Llama 3.1 405B",
            "Jul 23, 2024",
            "",
            "~243 GB Q4",
            "Llama 3.1 Community License",
            "Server/multi-GPU deployment",
            "128K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Largest Llama 3.1 open-weight model",
            "Server-class Meta model for frontier-style open-weight chat and reasoning experiments.",
            200,
            256,
            false),
        CatalogModel(
            "llama3.2:1b",
            "Llama 3.2 1B",
            "Sep 25, 2024",
            "",
            "~1.3 GB Q4",
            "Llama 3.2 Community License",
            "4 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Very fast on CPU or small GPUs",
            "Small local chat, summaries, routing, and low-cost fallback.",
            0,
            2,
            true),
        CatalogModel(
            "llama3.2:3b",
            "Llama 3.2 3B",
            "Sep 25, 2024",
            "",
            "~2.0 GB Q4",
            "Llama 3.2 Community License",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Good practical speed on 4 GB VRAM",
            "General local chat and review when you want a Meta-family baseline.",
            3.5,
            4,
            true),
        CatalogModel(
            "llama3.2-vision:11b",
            "Llama 3.2 Vision 11B",
            "Sep 25, 2024",
            "",
            "~7.9 GB Q4",
            "Llama 3.2 Community License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Meta vision/chat model",
            "Image-aware Llama route for screenshots, UI notes, document images, and visual assistant tasks.",
            10,
            12,
            false),
        CatalogModel(
            "llama3.2-vision:90b",
            "Llama 3.2 Vision 90B",
            "Sep 25, 2024",
            "",
            "~55 GB Q4",
            "Llama 3.2 Community License",
            "128 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large Meta vision/chat model",
            "Server-class visual reasoning and multimodal chat with the Llama ecosystem.",
            50,
            64,
            false),
        CatalogModel(
            "llama3.3:70b",
            "Llama 3.3 70B",
            "Dec 6, 2024",
            "",
            "~43 GB Q4",
            "Llama 3.3 Community License",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Workstation-class local model",
            "Strong general reasoning and review for large local setups.",
            48,
            64,
            false),
        CatalogModel(
            "llama4:16x17b",
            "Llama 4 Scout 16x17B",
            "Apr 5, 2025",
            "",
            "~67 GB Q4",
            "Llama 4 Community License",
            "128 GB RAM; 80 GB+ VRAM recommended",
            "10M",
            "8K-16K on large GPUs",
            "Use 8K-16K for CC work; 10M context is for specialized long-context setups.",
            "Very large multimodal MoE",
            "Long-context multimodal review on serious workstation/server hardware.",
            64,
            80,
            false),
        CatalogModel(
            "llama4:128x17b",
            "Llama 4 Maverick 128x17B",
            "Apr 5, 2025",
            "",
            "~245 GB Q4",
            "Llama 4 Community License",
            "384 GB RAM; multi-GPU/server recommended",
            "1M",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class multimodal MoE",
            "Top-end local Llama multimodal experiments on specialized hardware.",
            192,
            256,
            false),

    ];
}
