// CC-DESC: DeepSeek, GLM, and coding-specialized catalog slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> DeepSeekAndCodingCatalog { get; } =
    [
        CatalogModel(
            "deepseek-v4-flash:cloud",
            "DeepSeek V4 Flash Cloud",
            "Apr 2026",
            "",
            "Ollama Cloud",
            "DeepSeek License",
            "Ollama account/cloud access; no local VRAM",
            "1M",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud long-context reasoning model",
            "Efficient DeepSeek route for long-context planning, coding, math, and agentic tool workflows.",
            0,
            0,
            true),
        CatalogModel(
            "deepseek-v4-pro:cloud",
            "DeepSeek V4 Pro Cloud",
            "Apr 2026",
            "",
            "Ollama Cloud",
            "DeepSeek License",
            "Ollama account/cloud access; no local VRAM",
            "1M",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud frontier DeepSeek model",
            "Hard reasoning, coding, and long-context analysis when local hardware is not the limiting factor.",
            0,
            0,
            true),
        CatalogModel(
            "deepseek-v3.2:cloud",
            "DeepSeek V3.2 Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "DeepSeek License",
            "Ollama account/cloud access; no local VRAM",
            "160K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud DeepSeek agent/reasoning model",
            "Strong open DeepSeek route for code, reasoning, and tool-use tasks.",
            0,
            0,
            true),
        CatalogModel(
            "deepseek-v3.1:671b-cloud",
            "DeepSeek V3.1 Terminus Cloud",
            "Aug 2025",
            "",
            "Ollama Cloud",
            "DeepSeek License",
            "Ollama account/cloud access; no local VRAM",
            "160K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud hybrid reasoning/non-thinking model",
            "DeepSeek V3.1 route for coding, long-context chat, and tool work without server-class hardware.",
            0,
            0,
            true),
        CatalogModel(
            "deepseek-v3.1:671b",
            "DeepSeek V3.1 Terminus 671B",
            "Aug 2025",
            "",
            "~404 GB Q4",
            "DeepSeek License",
            "512 GB RAM; multi-GPU/server recommended",
            "160K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Server-class DeepSeek hybrid model",
            "Open-weight DeepSeek comparison point for large local clusters and hosted private inference.",
            384,
            512,
            false),
        CatalogModel(
            "deepseek-v3:671b",
            "DeepSeek V3 671B",
            "Dec 2024",
            "",
            "~404 GB Q4",
            "DeepSeek License",
            "512 GB RAM; multi-GPU/server recommended",
            "160K",
            "8K-16K unless you have a server-class setup",
            LargeSourceBudget,
            "Classic DeepSeek MoE model",
            "Large open DeepSeek baseline for server-side chat, code, and reasoning comparisons.",
            384,
            512,
            false),
        CatalogModel(
            "deepseek-coder:1.3b",
            "DeepSeek Coder 1.3B",
            "Nov 2023",
            "",
            "~776 MB Q4",
            "DeepSeek License",
            "4 GB RAM; CPU works",
            "16K",
            "4K safe",
            FourKSourceBudget,
            "Tiny coding model",
            "Very small code completion, file classification, and quick coding notes.",
            0,
            1.5,
            true),
        CatalogModel(
            "deepseek-coder:6.7b",
            "DeepSeek Coder 6.7B",
            "Nov 2023",
            "",
            "~3.8 GB Q4",
            "DeepSeek License",
            "12 GB RAM; 8 GB+ VRAM recommended",
            "16K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Classic DeepSeek coding model",
            "Compact code generation, explanation, and patch review with English/Chinese training coverage.",
            5.5,
            8,
            false),
        CatalogModel(
            "deepseek-coder:33b",
            "DeepSeek Coder 33B",
            "Nov 2023",
            "",
            "~19 GB Q4",
            "DeepSeek License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "16K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large classic DeepSeek coding model",
            "High-memory code completion, architecture notes, and repository-level coding comparisons.",
            18,
            24,
            false),
        CatalogModel(
            "deepseek-coder-v2:16b",
            "DeepSeek Coder V2 16B",
            "Jun 2024",
            "",
            "~8.9 GB Q4",
            "DeepSeek License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Efficient MoE code model",
            "Coding, repo navigation, and multilingual code tasks with much lower active-parameter cost.",
            10,
            12,
            false),
        CatalogModel(
            "deepseek-coder-v2:236b",
            "DeepSeek Coder V2 236B",
            "Jun 2024",
            "",
            "~133 GB Q4",
            "DeepSeek License",
            "192 GB+ RAM; multi-GPU/server preferred",
            "128K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large DeepSeek code MoE",
            "Server-class open coding model for serious repository agents and cross-language code reasoning.",
            112,
            128,
            false),
        CatalogModel(
            "deepcoder:1.5b",
            "DeepCoder 1.5B",
            "Apr 2025",
            "",
            "~1.1 GB Q4",
            "MIT",
            "4 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Tiny open coding model",
            "Small coding assistant for quick fixes, snippets, and code-oriented routing.",
            0,
            2,
            true),
        CatalogModel(
            "deepcoder:14b",
            "DeepCoder 14B",
            "Apr 2025",
            "",
            "~9.0 GB Q4",
            "MIT",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "128K",
            "8K on 12 GB+",
            EightKSourceBudget,
            "Open code reasoning model",
            "Coding-heavy tasks, patch planning, and test-oriented reasoning on mid/high-memory machines.",
            10,
            12,
            false),
        CatalogModel(
            "glm-5.1:cloud",
            "GLM-5.1 Cloud",
            "Apr 2026",
            "",
            "Ollama Cloud",
            "Z.ai License",
            "Ollama account/cloud access; no local VRAM",
            "198K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud agentic engineering model",
            "Z.ai route for long-horizon coding, repo generation, terminal tasks, and careful tool planning.",
            0,
            0,
            true),
        CatalogModel(
            "glm-5:cloud",
            "GLM-5 Cloud",
            "Feb 2026",
            "",
            "Ollama Cloud",
            "MIT",
            "Ollama account/cloud access; no local VRAM",
            "198K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud Z.ai reasoning model",
            "GLM-5 route for complex systems engineering, coding, and English/Chinese agentic tasks.",
            0,
            0,
            true),
        CatalogModel(
            "glm-4.7:cloud",
            "GLM-4.7 Cloud",
            "Dec 2025",
            "",
            "Ollama Cloud",
            "Z.ai License",
            "Ollama account/cloud access; no local VRAM",
            "198K",
            "16K+ practical via cloud",
            LargeSourceBudget,
            "Cloud GLM coding model",
            "Z.ai cloud route for coding agents, UI generation, terminal tasks, and long-context chat.",
            0,
            0,
            true),
        CatalogModel(
            "glm-4.7-flash:q4_K_M",
            "GLM-4.7 Flash 30B-A3B Q4",
            "Jan 2026",
            "",
            "~19 GB Q4",
            "Z.ai License",
            "48 GB RAM; 24 GB+ VRAM recommended; recent Ollama required",
            "198K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Strong local 30B-class GLM",
            "Lightweight MoE GLM for coding, thinking, tool use, and long-context local experiments.",
            18,
            24,
            false),
        CatalogModel(
            "codegeex4:9b",
            "CodeGeeX4 9B",
            "Jun 2024",
            "",
            "~5.5 GB Q4",
            "CodeGeeX License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Chinese/English code model",
            "Zhipu/THUDM coding coverage for code completion, explanations, and multilingual developer tasks.",
            6.5,
            8,
            false),
        CatalogModel(
            "hf.co/bartowski/codegemma-2b-GGUF:Q4_K_M",
            "CodeGemma 2B Q4",
            "Apr 2024",
            "",
            "~1.63 GB Q4",
            "Gemma Terms of Use",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "8K",
            "4K safe",
            FourKSourceBudget,
            "Compact Google code completion model",
            "Fast code infill, completion-style prompts, and latency-sensitive coding experiments on 4 GB GPUs.",
            3,
            4,
            true),
        CatalogModel(
            "hf.co/bartowski/stable-code-instruct-3b-GGUF:Q4_K_M",
            "Stable Code Instruct 3B Q4",
            "Mar 2024",
            "",
            "~1.70 GB Q4",
            "Stable Code License",
            "6-8 GB RAM; 4 GB VRAM recommended",
            "16K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Compact code chat baseline",
            "Niche instruction-tuned coding model for snippets, explanations, and completion comparisons.",
            3,
            4,
            true),
        CatalogModel(
            "opencoder:1.5b",
            "OpenCoder 1.5B",
            "Nov 2024",
            "",
            "~1.1 GB Q4",
            "OpenCoder License",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Tiny reproducible code/chat model",
            "Small English/Chinese coding chat, completion, and local assistant routing.",
            0,
            2,
            true),
        CatalogModel(
            "opencoder:8b",
            "OpenCoder 8B",
            "Nov 2024",
            "",
            "~4.8 GB Q4",
            "OpenCoder License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Open reproducible coding model",
            "English/Chinese code chat, explanations, repo notes, and reproducible model comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "rnj-1:8b",
            "RNJ-1 8B",
            "Dec 2025",
            "",
            "~5.1 GB Q4",
            "Open-weight",
            "16 GB RAM; 8 GB+ VRAM recommended; Ollama 0.13.3+",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Code/STEM tool model",
            "Essential AI route for code generation, tool calling, STEM reasoning, and agent experiments.",
            6.5,
            8,
            false),
    ];
}
