// CC-DESC: global chat and specialized local model slice.

namespace ContextControl.Workbench.Services;

public sealed partial class LocalLlmService
{
    private static IReadOnlyList<LocalLlmCatalogModel> CoreOllamaGlobalSpecializedCatalog { get; } =
    [
        CatalogModel(
            "internlm2:1.8b",
            "InternLM2.5 1.8B",
            "Aug 2024",
            "",
            "~1.1 GB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "32K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Tiny InternLM reasoning/chat model",
            "Lightweight English/Chinese chat, summaries, and quick reasoning checks.",
            0,
            2,
            true),
        CatalogModel(
            "internlm2:7b",
            "InternLM2.5 7B",
            "Aug 2024",
            "",
            "~4.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "InternLM practical chat model",
            "English/Chinese assistant work, tool-use experiments, math, and general chat.",
            6.5,
            8,
            false),
        CatalogModel(
            "internlm2:1m",
            "InternLM2.5 7B 1M",
            "Aug 2024",
            "",
            "~4.5 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "256K",
            "8K-16K locally; larger windows need roomy memory",
            LargeSourceBudget,
            "Long-context InternLM variant",
            "Large-context reading and retrieval-style chat when you can spare the memory.",
            6.5,
            8,
            false),
        CatalogModel(
            "internlm2:20b",
            "InternLM2.5 20B",
            "Aug 2024",
            "",
            "~11 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K-16K on 16 GB+",
            LargeSourceBudget,
            "Larger InternLM chat/reasoning model",
            "Better reasoning and bilingual chat quality than the 7B route on workstation GPUs.",
            12,
            16,
            false),
        CatalogModel(
            "openthinker:7b",
            "OpenThinker 7B",
            "Feb 2025",
            "",
            "~4.7 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Compact open reasoning model",
            "Math, structured decisions, patch critique, and lightweight reasoning-style chat.",
            6.5,
            8,
            false),
        CatalogModel(
            "openthinker:32b",
            "OpenThinker 32B",
            "Feb 2025",
            "",
            "~20 GB Q4",
            "Apache 2.0",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large open reasoning model",
            "Heavier math, planning, and code-review reasoning when local memory is generous.",
            20,
            24,
            false),
        CatalogModel(
            "wizardlm2:7b",
            "WizardLM2 7B",
            "Apr 2024",
            "",
            "~4.1 GB Q4",
            "Microsoft Research License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Classic compact instruction model",
            "General chat, instruction following, multilingual prompts, and comparison baselines.",
            6.5,
            8,
            false),
        CatalogModel(
            "wizardlm2:8x22b",
            "WizardLM2 8x22B",
            "Apr 2024",
            "",
            "~80 GB Q4",
            "Microsoft Research License",
            "128 GB+ RAM; multi-GPU/server preferred",
            "64K",
            "8K-16K on server GPUs",
            LargeSourceBudget,
            "Large MoE instruction model",
            "Server-class chat, reasoning, and multilingual instruction-following comparisons.",
            80,
            96,
            false),
        CatalogModel(
            "llama3-groq-tool-use:8b",
            "Llama 3 Groq Tool Use 8B",
            "Jul 2024",
            "",
            "~4.7 GB Q4",
            "Llama 3 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Tool/function-calling focused Llama",
            "Local agent experiments, structured tool calls, and function-calling comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "llama3-groq-tool-use:70b",
            "Llama 3 Groq Tool Use 70B",
            "Jul 2024",
            "",
            "~40 GB Q4",
            "Llama 3 Community License",
            "96 GB RAM; 48 GB+ VRAM recommended",
            "8K",
            "8K on large GPUs",
            LargeSourceBudget,
            "Large tool/function-calling model",
            "High-quality local/server function-calling, agent planning, and tool-use evaluation.",
            40,
            48,
            false),
        CatalogModel(
            "stablelm2:1.6b-chat",
            "Stable LM 2 1.6B Chat",
            "Jan 2024",
            "",
            "~983 MB Q4",
            "Stability AI NC Research License",
            "4 GB RAM; CPU works",
            "4K",
            "4K safe",
            FourKSourceBudget,
            "Tiny multilingual chat baseline",
            "Fast English and Western-European-language chat on very small hardware.",
            0,
            2,
            true),
        CatalogModel(
            "stablelm2:12b-chat",
            "Stable LM 2 12B Chat",
            "Jan 2024",
            "",
            "~7.0 GB Q4",
            "Stability AI NC Research License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "4K",
            "4K-8K on 12 GB+",
            EightKSourceBudget,
            "Larger Stable LM 2 chat model",
            "Multilingual assistant baseline when you want Stability AI lineage in the mix.",
            8,
            12,
            false),
        CatalogModel(
            "yi:6b",
            "Yi 1.5 6B",
            "May 2024",
            "",
            "~3.5 GB Q4",
            "Yi License",
            "12 GB RAM; 6-8 GB VRAM recommended",
            "4K",
            "4K safe",
            FourKSourceBudget,
            "Compact English/Chinese chat model",
            "Fast bilingual chat, summaries, and simple assistant work.",
            4,
            8,
            false),
        CatalogModel(
            "yi:9b",
            "Yi 1.5 9B",
            "May 2024",
            "",
            "~5.0 GB Q4",
            "Yi License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "4K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Mid-size English/Chinese chat model",
            "Better bilingual assistant quality than Yi 6B while still fitting consumer GPUs.",
            6.5,
            8,
            false),
        CatalogModel(
            "yi:34b",
            "Yi 1.5 34B",
            "May 2024",
            "",
            "~19 GB Q4",
            "Yi License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "4K",
            "4K-8K on large GPUs",
            LargeSourceBudget,
            "Large English/Chinese chat model",
            "Higher-quality bilingual chat and comparison baseline for Chinese/English workflows.",
            18,
            24,
            false),
        CatalogModel(
            "yi-coder:1.5b",
            "Yi Coder 1.5B",
            "Sep 2024",
            "",
            "~866 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "128K",
            "4K safe, 8K maybe okay",
            FourKSourceBudget,
            "Tiny code/chat model",
            "Fast code completion, snippets, and lightweight coding chat across many languages.",
            0,
            2,
            true),
        CatalogModel(
            "yi-coder:9b",
            "Yi Coder 9B",
            "Sep 2024",
            "",
            "~5.0 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K on 8 GB+; larger windows need memory",
            EightKSourceBudget,
            "Long-context code/chat model",
            "Coding assistant work, repository Q&A, and long-context code completion experiments.",
            6.5,
            8,
            false),
        CatalogModel(
            "openchat:7b",
            "OpenChat 3.5 7B",
            "Jan 2024",
            "",
            "~4.1 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "8K",
            "4K-8K on 8 GB+",
            EightKSourceBudget,
            "Open instruction/chat baseline",
            "General chat, coding tasks, and legacy open-model comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "neural-chat:7b",
            "Neural Chat 7B",
            "Nov 2023",
            "",
            "~4.1 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Intel/Mistral chat fine-tune",
            "General chatbot use, domain prompts, and older open chat comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "mistral-nemo:12b",
            "Mistral NeMo 12B",
            "Jul 2024",
            "",
            "~7.1 GB Q4",
            "Apache 2.0",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "1000K",
            "8K-16K locally; 128K+ only with roomy memory",
            LargeSourceBudget,
            "Long-context Mistral/NVIDIA model",
            "Strong mid-size chat, coding, and long-context assistant work.",
            8,
            12,
            false),
        CatalogModel(
            "mistral-small:22b",
            "Mistral Small 3 22B",
            "Jan 2025",
            "",
            "~13 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K-16K on 16 GB+",
            LargeSourceBudget,
            "Dense Mistral agentic chat model",
            "Fast conversational agents, function calling, JSON output, and code/math chat.",
            13,
            16,
            false),
        CatalogModel(
            "mistral-small:24b",
            "Mistral Small 3 24B",
            "Jan 2025",
            "",
            "~14 GB Q4",
            "Apache 2.0",
            "32 GB RAM; 16 GB+ VRAM recommended",
            "32K",
            "8K-16K on 16 GB+",
            LargeSourceBudget,
            "Dense Mistral agentic chat model",
            "Knowledge-dense local assistant for tool use, structured output, and general chat.",
            14,
            16,
            false),
        CatalogModel(
            "athene-v2:72b",
            "Athene V2 72B",
            "Nov 2024",
            "",
            "~47 GB Q4",
            "Nexusflow License",
            "96 GB RAM; 64 GB+ VRAM recommended",
            "32K",
            "8K-16K on workstation/server GPUs",
            LargeSourceBudget,
            "Qwen-derived chat/code/math model",
            "Large chat, code completion, math, and long-form log extraction on server-class hardware.",
            48,
            64,
            false),
        CatalogModel(
            "medgemma:4b",
            "MedGemma 4B",
            "Apr 2026",
            "",
            "~3.3 GB Q4",
            "Gemma Terms of Use",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K-8K for responsive local use",
            EightKSourceBudget,
            "Medical text/image comprehension model",
            "Specialized medical literature and image-grounded assistant experiments; not a diagnostic authority.",
            3.5,
            4,
            true),
        CatalogModel(
            "medgemma:27b",
            "MedGemma 27B",
            "Apr 2026",
            "",
            "~17 GB Q4",
            "Gemma Terms of Use",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "128K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "Large medical text/image comprehension model",
            "Specialized healthcare AI prototyping and medical document/image analysis; not a diagnostic authority.",
            18,
            24,
            false),
        CatalogModel(
            "medgemma1.5:4b",
            "MedGemma 1.5 4B",
            "Apr 2026",
            "",
            "~3.3 GB Q4",
            "Gemma Terms of Use",
            "8 GB RAM; 4 GB VRAM recommended",
            "128K",
            "4K-8K for responsive local use",
            EightKSourceBudget,
            "Updated medical text/image model",
            "Newer 4B MedGemma route for medical text reasoning and image-grounded prototypes; not a diagnostic authority.",
            3.5,
            4,
            false),

        CatalogModel(
            "tinyllama:1.1b",
            "TinyLlama 1.1B Chat",
            "Jan 2024",
            "",
            "~638 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "2K",
            "2K safe",
            FourKSourceBudget,
            "Extremely small local chat baseline",
            "Tiny weak-PC assistant baseline for quick routing, smoke tests, and offline chat experiments.",
            0,
            1,
            true),
        CatalogModel(
            "tinydolphin:1.1b",
            "TinyDolphin 1.1B",
            "Mar 2024",
            "",
            "~637 MB Q4",
            "Apache 2.0",
            "4 GB RAM; CPU works",
            "4K",
            "4K safe",
            FourKSourceBudget,
            "Tiny instruction-tuned chat model",
            "Small local assistant and instruction-following comparison for very constrained machines.",
            0,
            1,
            true),
        CatalogModel(
            "orca-mini:3b",
            "Orca Mini 3B",
            "Jun 2023",
            "",
            "~2.0 GB Q4",
            "Apache 2.0",
            "6 GB RAM; CPU works",
            "2K",
            "2K safe",
            FourKSourceBudget,
            "Entry-level general chat model",
            "Legacy weak-PC comparison route for simple chat, summaries, and instruction-following tests.",
            0,
            2,
            true),
        CatalogModel(
            "orca-mini:7b",
            "Orca Mini 7B",
            "Jun 2023",
            "",
            "~3.8 GB Q4",
            "Apache 2.0",
            "12 GB RAM; 6-8 GB VRAM recommended",
            "4K",
            "4K safe",
            FourKSourceBudget,
            "Classic small general chat model",
            "Legacy local assistant baseline when comparing old 7B chat behavior against newer small models.",
            4,
            8,
            false),
        CatalogModel(
            "openhermes:v2.5",
            "OpenHermes 2.5 7B",
            "Nov 2023",
            "",
            "~4.1 GB Q4",
            "Apache 2.0",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "32K",
            "8K on 8 GB+",
            EightKSourceBudget,
            "Open-data Mistral instruction fine-tune",
            "General chat, role-following, structured answers, and classic local instruction-model comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "dolphin3:8b",
            "Dolphin 3.0 8B",
            "Feb 2025",
            "",
            "~4.9 GB Q4",
            "Llama 3.1 Community License",
            "16 GB RAM; 8 GB+ VRAM recommended",
            "128K",
            "8K-16K on 8 GB+",
            LargeSourceBudget,
            "General local agent/tool model",
            "Coding, math, function calling, agentic local chat, and long-context assistant comparisons.",
            6.5,
            8,
            false),
        CatalogModel(
            "nous-hermes2:10.7b",
            "Nous Hermes 2 Solar 10.7B",
            "Jan 2024",
            "",
            "~6.1 GB Q4",
            "Nous Research License",
            "24 GB RAM; 12 GB+ VRAM recommended",
            "4K",
            "4K-8K on 12 GB+",
            EightKSourceBudget,
            "Scientific/coding chat fine-tune",
            "Classic Hermes route for scientific discussion, coding prompts, and conversational comparisons.",
            8,
            12,
            false),
        CatalogModel(
            "nous-hermes2:34b",
            "Nous Hermes 2 Yi 34B",
            "Dec 2023",
            "",
            "~19 GB Q4",
            "Nous Research License",
            "48 GB RAM; 24 GB+ VRAM recommended",
            "4K",
            "4K-8K on large GPUs",
            LargeSourceBudget,
            "Large Yi-based Hermes chat model",
            "Higher-quality classic Hermes baseline for coding, science, and long-form assistant work.",
            18,
            24,
            false),
        CatalogModel(
            "nous-hermes2-mixtral:8x7b",
            "Nous Hermes 2 Mixtral 8x7B",
            "Jan 2024",
            "",
            "~26 GB Q4",
            "Nous Research License",
            "64 GB RAM; 32 GB+ VRAM recommended",
            "32K",
            "8K-16K on large GPUs",
            LargeSourceBudget,
            "MoE Hermes instruction model",
            "Large local MoE chat, coding, and instruction-following comparisons.",
            26,
            32,
            false),
    ];
}
